// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/InterfaceValue.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/interface_value.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "rosidl_runtime_c/string_functions.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"


// Generated
#include "ROS2InterfaceValue.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSInterfaceValue
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FString> InterfaceNames;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<double> Values;

	

	FROSInterfaceValue()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__InterfaceValue& in_ros_data)
	{
    	UROS2Utils::StringSequenceROSToUEArray<rosidl_runtime_c__String>(in_ros_data.interface_names.data, InterfaceNames, in_ros_data.interface_names.size);

		UROS2Utils::SequenceROSToUEArray<double, double>(in_ros_data.values.data, Values, in_ros_data.values.size);

		
	}

	void SetROS2(control_msgs__msg__InterfaceValue& out_ros_data) const
	{
    	if (out_ros_data.interface_names.data) {
		rosidl_runtime_c__String__Sequence__fini(&out_ros_data.interface_names);
		}
		if (!rosidl_runtime_c__String__Sequence__init(&out_ros_data.interface_names, InterfaceNames.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.interface_names  "));}
		UROS2Utils::StringArrayUEToROSSequence(InterfaceNames, out_ros_data.interface_names.data, InterfaceNames.Num());

		if (out_ros_data.values.data) {
		rosidl_runtime_c__float64__Sequence__fini(&out_ros_data.values);
		}
		if (!rosidl_runtime_c__float64__Sequence__init(&out_ros_data.values, Values.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.values  "));}
		UROS2Utils::ArrayUEToROSSequence<double, double>(Values, out_ros_data.values.data, Values.Num());

		
	}
};

UCLASS()
class RCLUE_API UROS2InterfaceValueMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSInterfaceValue& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSInterfaceValue& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__InterfaceValue interface_value_msg;
};