// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/MotionArgument.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/motion_argument.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)


// Generated
#include "ROS2MotionArgument.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSMotionArgument
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString Name;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Value = 0.f;

	

	FROSMotionArgument()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__MotionArgument& in_ros_data)
	{
    	Name = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.name);

		Value = in_ros_data.value;

		
	}

	void SetROS2(control_msgs__msg__MotionArgument& out_ros_data) const
	{
    	UROS2Utils::StringUEToROS(Name, out_ros_data.name);

		out_ros_data.value = Value;

		
	}
};

UCLASS()
class RCLUE_API UROS2MotionArgumentMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSMotionArgument& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSMotionArgument& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__MotionArgument motion_argument_msg;
};