// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/MultiDOFCommand.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/multi_dof_command.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "rosidl_runtime_c/string_functions.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"


// Generated
#include "ROS2MultiDOFCommand.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSMultiDOFCommand
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FString> DofNames;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<double> Values;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<double> ValuesDot;

	

	FROSMultiDOFCommand()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__MultiDOFCommand& in_ros_data)
	{
    	UROS2Utils::StringSequenceROSToUEArray<rosidl_runtime_c__String>(in_ros_data.dof_names.data, DofNames, in_ros_data.dof_names.size);

		UROS2Utils::SequenceROSToUEArray<double, double>(in_ros_data.values.data, Values, in_ros_data.values.size);

		UROS2Utils::SequenceROSToUEArray<double, double>(in_ros_data.values_dot.data, ValuesDot, in_ros_data.values_dot.size);

		
	}

	void SetROS2(control_msgs__msg__MultiDOFCommand& out_ros_data) const
	{
    	if (out_ros_data.dof_names.data) {
		rosidl_runtime_c__String__Sequence__fini(&out_ros_data.dof_names);
		}
		if (!rosidl_runtime_c__String__Sequence__init(&out_ros_data.dof_names, DofNames.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.dof_names  "));}
		UROS2Utils::StringArrayUEToROSSequence(DofNames, out_ros_data.dof_names.data, DofNames.Num());

		if (out_ros_data.values.data) {
		rosidl_runtime_c__float64__Sequence__fini(&out_ros_data.values);
		}
		if (!rosidl_runtime_c__float64__Sequence__init(&out_ros_data.values, Values.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.values  "));}
		UROS2Utils::ArrayUEToROSSequence<double, double>(Values, out_ros_data.values.data, Values.Num());

		if (out_ros_data.values_dot.data) {
		rosidl_runtime_c__float64__Sequence__fini(&out_ros_data.values_dot);
		}
		if (!rosidl_runtime_c__float64__Sequence__init(&out_ros_data.values_dot, ValuesDot.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.values_dot  "));}
		UROS2Utils::ArrayUEToROSSequence<double, double>(ValuesDot, out_ros_data.values_dot.data, ValuesDot.Num());

		
	}
};

UCLASS()
class RCLUE_API UROS2MultiDOFCommandMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSMultiDOFCommand& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSMultiDOFCommand& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__MultiDOFCommand multi_dof_command_msg;
};