// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/JointControllerState.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/joint_controller_state.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"


// Generated
#include "ROS2JointCtrllerState.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSJointCtrllerState
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double SetPoint = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double ProcessValue = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double ProcessValueDot = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Error = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double TimeStep = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Command = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double P = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double I = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double D = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double IClamp = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bAntiwindup = false;

	

	FROSJointCtrllerState()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__JointControllerState& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		SetPoint = in_ros_data.set_point;

		ProcessValue = in_ros_data.process_value;

		ProcessValueDot = in_ros_data.process_value_dot;

		Error = in_ros_data.error;

		TimeStep = in_ros_data.time_step;

		Command = in_ros_data.command;

		P = in_ros_data.p;

		I = in_ros_data.i;

		D = in_ros_data.d;

		IClamp = in_ros_data.i_clamp;

		bAntiwindup = in_ros_data.antiwindup;

		
	}

	void SetROS2(control_msgs__msg__JointControllerState& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		out_ros_data.set_point = SetPoint;

		out_ros_data.process_value = ProcessValue;

		out_ros_data.process_value_dot = ProcessValueDot;

		out_ros_data.error = Error;

		out_ros_data.time_step = TimeStep;

		out_ros_data.command = Command;

		out_ros_data.p = P;

		out_ros_data.i = I;

		out_ros_data.d = D;

		out_ros_data.i_clamp = IClamp;

		out_ros_data.antiwindup = bAntiwindup;

		
	}
};

UCLASS()
class RCLUE_API UROS2JointCtrllerStateMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSJointCtrllerState& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSJointCtrllerState& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__JointControllerState joint_controller_state_msg;
};