// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/SpeedScalingFactor.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/speed_scaling_factor.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)


// Generated
#include "ROS2SpeedScalingFactor.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSSpeedScalingFactor
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Factor = 0.f;

	

	FROSSpeedScalingFactor()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__SpeedScalingFactor& in_ros_data)
	{
    	Factor = in_ros_data.factor;

		
	}

	void SetROS2(control_msgs__msg__SpeedScalingFactor& out_ros_data) const
	{
    	out_ros_data.factor = Factor;

		
	}
};

UCLASS()
class RCLUE_API UROS2SpeedScalingFactorMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSSpeedScalingFactor& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSSpeedScalingFactor& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__SpeedScalingFactor speed_scaling_factor_msg;
};