// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/SteeringControllerStatus.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/steering_controller_status.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"


// Generated
#include "ROS2SteeringCtrllerStatus.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSSteeringCtrllerStatus
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<double> TractionWheelsPosition;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<double> TractionWheelsVelocity;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<double> SteerPositions;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<double> LinearVelocityCommand;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<double> SteeringAngleCommand;

	

	FROSSteeringCtrllerStatus()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__SteeringControllerStatus& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		UROS2Utils::SequenceROSToUEArray<double, double>(in_ros_data.traction_wheels_position.data, TractionWheelsPosition, in_ros_data.traction_wheels_position.size);

		UROS2Utils::SequenceROSToUEArray<double, double>(in_ros_data.traction_wheels_velocity.data, TractionWheelsVelocity, in_ros_data.traction_wheels_velocity.size);

		UROS2Utils::SequenceROSToUEArray<double, double>(in_ros_data.steer_positions.data, SteerPositions, in_ros_data.steer_positions.size);

		UROS2Utils::SequenceROSToUEArray<double, double>(in_ros_data.linear_velocity_command.data, LinearVelocityCommand, in_ros_data.linear_velocity_command.size);

		UROS2Utils::SequenceROSToUEArray<double, double>(in_ros_data.steering_angle_command.data, SteeringAngleCommand, in_ros_data.steering_angle_command.size);

		
	}

	void SetROS2(control_msgs__msg__SteeringControllerStatus& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		if (out_ros_data.traction_wheels_position.data) {
		rosidl_runtime_c__float64__Sequence__fini(&out_ros_data.traction_wheels_position);
		}
		if (!rosidl_runtime_c__float64__Sequence__init(&out_ros_data.traction_wheels_position, TractionWheelsPosition.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.traction_wheels_position  "));}
		UROS2Utils::ArrayUEToROSSequence<double, double>(TractionWheelsPosition, out_ros_data.traction_wheels_position.data, TractionWheelsPosition.Num());

		if (out_ros_data.traction_wheels_velocity.data) {
		rosidl_runtime_c__float64__Sequence__fini(&out_ros_data.traction_wheels_velocity);
		}
		if (!rosidl_runtime_c__float64__Sequence__init(&out_ros_data.traction_wheels_velocity, TractionWheelsVelocity.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.traction_wheels_velocity  "));}
		UROS2Utils::ArrayUEToROSSequence<double, double>(TractionWheelsVelocity, out_ros_data.traction_wheels_velocity.data, TractionWheelsVelocity.Num());

		if (out_ros_data.steer_positions.data) {
		rosidl_runtime_c__float64__Sequence__fini(&out_ros_data.steer_positions);
		}
		if (!rosidl_runtime_c__float64__Sequence__init(&out_ros_data.steer_positions, SteerPositions.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.steer_positions  "));}
		UROS2Utils::ArrayUEToROSSequence<double, double>(SteerPositions, out_ros_data.steer_positions.data, SteerPositions.Num());

		if (out_ros_data.linear_velocity_command.data) {
		rosidl_runtime_c__float64__Sequence__fini(&out_ros_data.linear_velocity_command);
		}
		if (!rosidl_runtime_c__float64__Sequence__init(&out_ros_data.linear_velocity_command, LinearVelocityCommand.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.linear_velocity_command  "));}
		UROS2Utils::ArrayUEToROSSequence<double, double>(LinearVelocityCommand, out_ros_data.linear_velocity_command.data, LinearVelocityCommand.Num());

		if (out_ros_data.steering_angle_command.data) {
		rosidl_runtime_c__float64__Sequence__fini(&out_ros_data.steering_angle_command);
		}
		if (!rosidl_runtime_c__float64__Sequence__init(&out_ros_data.steering_angle_command, SteeringAngleCommand.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.steering_angle_command  "));}
		UROS2Utils::ArrayUEToROSSequence<double, double>(SteeringAngleCommand, out_ros_data.steering_angle_command.data, SteeringAngleCommand.Num());

		
	}
};

UCLASS()
class RCLUE_API UROS2SteeringCtrllerStatusMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSSteeringCtrllerStatus& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSSteeringCtrllerStatus& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__SteeringControllerStatus steering_controller_status_msg;
};