// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/GripperCommand.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/gripper_command.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)


// Generated
#include "ROS2GripperCommand.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSGripperCommand
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Position = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double MaxEffort = 0.f;

	

	FROSGripperCommand()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__GripperCommand& in_ros_data)
	{
    	Position = in_ros_data.position;

		MaxEffort = in_ros_data.max_effort;

		
	}

	void SetROS2(control_msgs__msg__GripperCommand& out_ros_data) const
	{
    	out_ros_data.position = Position;

		out_ros_data.max_effort = MaxEffort;

		
	}
};

UCLASS()
class RCLUE_API UROS2GripperCommandMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSGripperCommand& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSGripperCommand& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__GripperCommand gripper_command_msg;
};