// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/JointTrajectoryControllerState.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/joint_trajectory_controller_state.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"
#include "rosidl_runtime_c/string_functions.h"
#include "Msgs/ROS2JointTrajPoint.h"
#include "Msgs/ROS2JointTrajPoint.h"
#include "Msgs/ROS2JointTrajPoint.h"
#include "Msgs/ROS2JointTrajPoint.h"
#include "rosidl_runtime_c/string_functions.h"
#include "Msgs/ROS2MultiDOFJointTrajPoint.h"
#include "Msgs/ROS2MultiDOFJointTrajPoint.h"
#include "Msgs/ROS2MultiDOFJointTrajPoint.h"
#include "Msgs/ROS2MultiDOFJointTrajPoint.h"


// Generated
#include "ROS2JointTrajCtrllerState.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSJointTrajCtrllerState
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FString> JointNames;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSJointTrajPoint Reference;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSJointTrajPoint Feedback;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSJointTrajPoint Error;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSJointTrajPoint Output;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FString> MultiDofJointNames;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSMultiDOFJointTrajPoint MultiDofReference;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSMultiDOFJointTrajPoint MultiDofFeedback;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSMultiDOFJointTrajPoint MultiDofError;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSMultiDOFJointTrajPoint MultiDofOutput;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double SpeedScalingFactor = 0.f;

	

	FROSJointTrajCtrllerState()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__JointTrajectoryControllerState& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		UROS2Utils::StringSequenceROSToUEArray<rosidl_runtime_c__String>(in_ros_data.joint_names.data, JointNames, in_ros_data.joint_names.size);

		Reference.SetFromROS2(in_ros_data.reference);

		Feedback.SetFromROS2(in_ros_data.feedback);

		Error.SetFromROS2(in_ros_data.error);

		Output.SetFromROS2(in_ros_data.output);

		UROS2Utils::StringSequenceROSToUEArray<rosidl_runtime_c__String>(in_ros_data.multi_dof_joint_names.data, MultiDofJointNames, in_ros_data.multi_dof_joint_names.size);

		MultiDofReference.SetFromROS2(in_ros_data.multi_dof_reference);

		MultiDofFeedback.SetFromROS2(in_ros_data.multi_dof_feedback);

		MultiDofError.SetFromROS2(in_ros_data.multi_dof_error);

		MultiDofOutput.SetFromROS2(in_ros_data.multi_dof_output);

		SpeedScalingFactor = in_ros_data.speed_scaling_factor;

		
	}

	void SetROS2(control_msgs__msg__JointTrajectoryControllerState& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		if (out_ros_data.joint_names.data) {
		rosidl_runtime_c__String__Sequence__fini(&out_ros_data.joint_names);
		}
		if (!rosidl_runtime_c__String__Sequence__init(&out_ros_data.joint_names, JointNames.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.joint_names  "));}
		UROS2Utils::StringArrayUEToROSSequence(JointNames, out_ros_data.joint_names.data, JointNames.Num());

		Reference.SetROS2(out_ros_data.reference);

		Feedback.SetROS2(out_ros_data.feedback);

		Error.SetROS2(out_ros_data.error);

		Output.SetROS2(out_ros_data.output);

		if (out_ros_data.multi_dof_joint_names.data) {
		rosidl_runtime_c__String__Sequence__fini(&out_ros_data.multi_dof_joint_names);
		}
		if (!rosidl_runtime_c__String__Sequence__init(&out_ros_data.multi_dof_joint_names, MultiDofJointNames.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.multi_dof_joint_names  "));}
		UROS2Utils::StringArrayUEToROSSequence(MultiDofJointNames, out_ros_data.multi_dof_joint_names.data, MultiDofJointNames.Num());

		MultiDofReference.SetROS2(out_ros_data.multi_dof_reference);

		MultiDofFeedback.SetROS2(out_ros_data.multi_dof_feedback);

		MultiDofError.SetROS2(out_ros_data.multi_dof_error);

		MultiDofOutput.SetROS2(out_ros_data.multi_dof_output);

		out_ros_data.speed_scaling_factor = SpeedScalingFactor;

		
	}
};

UCLASS()
class RCLUE_API UROS2JointTrajCtrllerStateMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSJointTrajCtrllerState& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSJointTrajCtrllerState& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__JointTrajectoryControllerState joint_trajectory_controller_state_msg;
};