// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/PidState.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/pid_state.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"
#include "Msgs/ROS2Duration.h"


// Generated
#include "ROS2PidState.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSPidState
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSDuration Timestep;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Error = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double ErrorDot = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double PError = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double IError = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double DError = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double PTerm = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double ITerm = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double DTerm = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double IMax = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double IMin = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Output = 0.f;

	

	FROSPidState()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__PidState& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		Timestep.SetFromROS2(in_ros_data.timestep);

		Error = in_ros_data.error;

		ErrorDot = in_ros_data.error_dot;

		PError = in_ros_data.p_error;

		IError = in_ros_data.i_error;

		DError = in_ros_data.d_error;

		PTerm = in_ros_data.p_term;

		ITerm = in_ros_data.i_term;

		DTerm = in_ros_data.d_term;

		IMax = in_ros_data.i_max;

		IMin = in_ros_data.i_min;

		Output = in_ros_data.output;

		
	}

	void SetROS2(control_msgs__msg__PidState& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		Timestep.SetROS2(out_ros_data.timestep);

		out_ros_data.error = Error;

		out_ros_data.error_dot = ErrorDot;

		out_ros_data.p_error = PError;

		out_ros_data.i_error = IError;

		out_ros_data.d_error = DError;

		out_ros_data.p_term = PTerm;

		out_ros_data.i_term = ITerm;

		out_ros_data.d_term = DTerm;

		out_ros_data.i_max = IMax;

		out_ros_data.i_min = IMin;

		out_ros_data.output = Output;

		
	}
};

UCLASS()
class RCLUE_API UROS2PidStateMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSPidState& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSPidState& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__PidState pid_state_msg;
};