// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/JointTolerance.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/joint_tolerance.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)


// Generated
#include "ROS2JointTolerance.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSJointTolerance
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString Name;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Position = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Velocity = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Acceleration = 0.f;

	

	FROSJointTolerance()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__JointTolerance& in_ros_data)
	{
    	Name = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.name);

		Position = in_ros_data.position;

		Velocity = in_ros_data.velocity;

		Acceleration = in_ros_data.acceleration;

		
	}

	void SetROS2(control_msgs__msg__JointTolerance& out_ros_data) const
	{
    	UROS2Utils::StringUEToROS(Name, out_ros_data.name);

		out_ros_data.position = Position;

		out_ros_data.velocity = Velocity;

		out_ros_data.acceleration = Acceleration;

		
	}
};

UCLASS()
class RCLUE_API UROS2JointToleranceMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSJointTolerance& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSJointTolerance& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__JointTolerance joint_tolerance_msg;
};