// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/MultiDOFStateStamped.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/multi_dof_state_stamped.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"
#include "Msgs/ROS2SingleDOFState.h"
#include "control_msgs/msg/detail/single_dof_state__functions.h"


// Generated
#include "ROS2MultiDOFStateStamped.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSMultiDOFStateStamped
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FROSSingleDOFState> DofStates;

	

	FROSMultiDOFStateStamped()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__MultiDOFStateStamped& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		UROS2Utils::SequenceROSToUEArray<control_msgs__msg__SingleDOFState, FROSSingleDOFState>(in_ros_data.dof_states.data, DofStates, in_ros_data.dof_states.size);

		
	}

	void SetROS2(control_msgs__msg__MultiDOFStateStamped& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		if (out_ros_data.dof_states.data) {
		control_msgs__msg__SingleDOFState__Sequence__fini(&out_ros_data.dof_states);
		}
		if (!control_msgs__msg__SingleDOFState__Sequence__init(&out_ros_data.dof_states, DofStates.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.dof_states  "));}
		UROS2Utils::ArrayUEToROSSequence<control_msgs__msg__SingleDOFState, FROSSingleDOFState>(DofStates, out_ros_data.dof_states.data, DofStates.Num());

		
	}
};

UCLASS()
class RCLUE_API UROS2MultiDOFStateStampedMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSMultiDOFStateStamped& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSMultiDOFStateStamped& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__MultiDOFStateStamped multi_dof_state_stamped_msg;
};