// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/SingleDOFStateStamped.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/single_dof_state_stamped.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"
#include "Msgs/ROS2SingleDOFState.h"


// Generated
#include "ROS2SingleDOFStateStamped.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSSingleDOFStateStamped
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSSingleDOFState DofState;

	

	FROSSingleDOFStateStamped()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__SingleDOFStateStamped& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		DofState.SetFromROS2(in_ros_data.dof_state);

		
	}

	void SetROS2(control_msgs__msg__SingleDOFStateStamped& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		DofState.SetROS2(out_ros_data.dof_state);

		
	}
};

UCLASS()
class RCLUE_API UROS2SingleDOFStateStampedMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSSingleDOFStateStamped& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSSingleDOFStateStamped& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__SingleDOFStateStamped single_dof_state_stamped_msg;
};