// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/DynamicInterfaceValues.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/dynamic_interface_values.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"
#include "Msgs/ROS2InterfaceValue.h"
#include "Msgs/ROS2InterfaceValue.h"


// Generated
#include "ROS2DynamicInterfaceValues.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSDynamicInterfaceValues
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSInterfaceValue States;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSInterfaceValue Commands;

	

	FROSDynamicInterfaceValues()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__DynamicInterfaceValues& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		States.SetFromROS2(in_ros_data.states);

		Commands.SetFromROS2(in_ros_data.commands);

		
	}

	void SetROS2(control_msgs__msg__DynamicInterfaceValues& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		States.SetROS2(out_ros_data.states);

		Commands.SetROS2(out_ros_data.commands);

		
	}
};

UCLASS()
class RCLUE_API UROS2DynamicInterfaceValuesMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSDynamicInterfaceValues& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSDynamicInterfaceValues& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__DynamicInterfaceValues dynamic_interface_values_msg;
};