// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from clf_audio_msgs/msg/AudioData.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "clf_audio_msgs/msg/audio_data.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "rosidl_runtime_c/primitives_sequence_functions.h"


// Generated
#include "ROS2AudioData.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSAudioData
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere)
	TArray<uint8> Data;

	

	FROSAudioData()
	{
		
	}

	void SetFromROS2(const clf_audio_msgs__msg__AudioData& in_ros_data)
	{
    	UROS2Utils::SequenceROSToUEArray<uint8, uint8>(in_ros_data.data.data, Data, in_ros_data.data.size);

		
	}

	void SetROS2(clf_audio_msgs__msg__AudioData& out_ros_data) const
	{
    	if (out_ros_data.data.data) {
		rosidl_runtime_c__uint8__Sequence__fini(&out_ros_data.data);
		}
		if (!rosidl_runtime_c__uint8__Sequence__init(&out_ros_data.data, Data.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.data  "));}
		UROS2Utils::ArrayUEToROSSequence<uint8, uint8>(Data, out_ros_data.data.data, Data.Num());

		
	}
};

UCLASS()
class RCLUE_API UROS2AudioDataMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSAudioData& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSAudioData& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	clf_audio_msgs__msg__AudioData audio_data_msg;
};