// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/JointComponentTolerance.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/joint_component_tolerance.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)


// Generated
#include "ROS2JointComponentTolerance.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSJointComponentTolerance
{
	GENERATED_BODY()

public:
		static constexpr uint16 X_AXIS = 1;
	static constexpr uint16 Y_AXIS = 2;
	static constexpr uint16 Z_AXIS = 3;
	static constexpr uint16 TRANSLATION = 4;
	static constexpr uint16 ROTATION = 5;


	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString JointName;

	UPROPERTY(EditAnywhere)
	uint16 Component = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Position = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Velocity = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Acceleration = 0.f;

	

	FROSJointComponentTolerance()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__JointComponentTolerance& in_ros_data)
	{
    	JointName = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.joint_name);

		Component = in_ros_data.component;

		Position = in_ros_data.position;

		Velocity = in_ros_data.velocity;

		Acceleration = in_ros_data.acceleration;

		
	}

	void SetROS2(control_msgs__msg__JointComponentTolerance& out_ros_data) const
	{
    	UROS2Utils::StringUEToROS(JointName, out_ros_data.joint_name);

		out_ros_data.component = Component;

		out_ros_data.position = Position;

		out_ros_data.velocity = Velocity;

		out_ros_data.acceleration = Acceleration;

		
	}
};

UCLASS()
class RCLUE_API UROS2JointComponentToleranceMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSJointComponentTolerance& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSJointComponentTolerance& Output) const;
	
	virtual void* Get() override;

	static uint16 CONST_X_AXIS()
	{
		return FROSJointComponentTolerance::X_AXIS;
	}
	static uint16 CONST_Y_AXIS()
	{
		return FROSJointComponentTolerance::Y_AXIS;
	}
	static uint16 CONST_Z_AXIS()
	{
		return FROSJointComponentTolerance::Z_AXIS;
	}
	static uint16 CONST_TRANSLATION()
	{
		return FROSJointComponentTolerance::TRANSLATION;
	}
	static uint16 CONST_ROTATION()
	{
		return FROSJointComponentTolerance::ROTATION;
	}
	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__JointComponentTolerance joint_component_tolerance_msg;
};