// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/DynamicInterfaceGroupValues.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/dynamic_interface_group_values.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"
#include "rosidl_runtime_c/string_functions.h"
#include "Msgs/ROS2InterfaceValue.h"
#include "control_msgs/msg/detail/interface_value__functions.h"


// Generated
#include "ROS2DynamicInterfaceGroupValues.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSDynamicInterfaceGroupValues
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FString> InterfaceGroups;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FROSInterfaceValue> InterfaceValues;

	

	FROSDynamicInterfaceGroupValues()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__DynamicInterfaceGroupValues& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		UROS2Utils::StringSequenceROSToUEArray<rosidl_runtime_c__String>(in_ros_data.interface_groups.data, InterfaceGroups, in_ros_data.interface_groups.size);

		UROS2Utils::SequenceROSToUEArray<control_msgs__msg__InterfaceValue, FROSInterfaceValue>(in_ros_data.interface_values.data, InterfaceValues, in_ros_data.interface_values.size);

		
	}

	void SetROS2(control_msgs__msg__DynamicInterfaceGroupValues& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		if (out_ros_data.interface_groups.data) {
		rosidl_runtime_c__String__Sequence__fini(&out_ros_data.interface_groups);
		}
		if (!rosidl_runtime_c__String__Sequence__init(&out_ros_data.interface_groups, InterfaceGroups.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.interface_groups  "));}
		UROS2Utils::StringArrayUEToROSSequence(InterfaceGroups, out_ros_data.interface_groups.data, InterfaceGroups.Num());

		if (out_ros_data.interface_values.data) {
		control_msgs__msg__InterfaceValue__Sequence__fini(&out_ros_data.interface_values);
		}
		if (!control_msgs__msg__InterfaceValue__Sequence__init(&out_ros_data.interface_values, InterfaceValues.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.interface_values  "));}
		UROS2Utils::ArrayUEToROSSequence<control_msgs__msg__InterfaceValue, FROSInterfaceValue>(InterfaceValues, out_ros_data.interface_values.data, InterfaceValues.Num());

		
	}
};

UCLASS()
class RCLUE_API UROS2DynamicInterfaceGroupValuesMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSDynamicInterfaceGroupValues& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSDynamicInterfaceGroupValues& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__DynamicInterfaceGroupValues dynamic_interface_group_values_msg;
};