// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from clf_ue_audio_msgs/msg/ReturnCode.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "clf_ue_audio_msgs/msg/return_code.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)


// Generated
#include "ROS2ReturnCode.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSReturnCode
{
	GENERATED_BODY()

public:
		static constexpr int8 SUCCESS = 0;
	static constexpr int8 ERROR = 1;


	UPROPERTY(EditAnywhere)
	int8 Code = 0;

	

	FROSReturnCode()
	{
		
	}

	void SetFromROS2(const clf_ue_audio_msgs__msg__ReturnCode& in_ros_data)
	{
    	Code = in_ros_data.code;

		
	}

	void SetROS2(clf_ue_audio_msgs__msg__ReturnCode& out_ros_data) const
	{
    	out_ros_data.code = Code;

		
	}
};

UCLASS()
class RCLUE_API UROS2ReturnCodeMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSReturnCode& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSReturnCode& Output) const;
	
	virtual void* Get() override;

	static int8 CONST_SUCCESS()
	{
		return FROSReturnCode::SUCCESS;
	}
	static int8 CONST_ERROR()
	{
		return FROSReturnCode::ERROR;
	}
	


private:
	virtual FString MsgToString() const override;

	clf_ue_audio_msgs__msg__ReturnCode return_code_msg;
};