// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/SingleDOFState.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/single_dof_state.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)


// Generated
#include "ROS2SingleDOFState.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSSingleDOFState
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString Name;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Reference = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Feedback = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double FeedbackDot = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Error = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double ErrorDot = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double TimeStep = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Output = 0.f;

	

	FROSSingleDOFState()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__SingleDOFState& in_ros_data)
	{
    	Name = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.name);

		Reference = in_ros_data.reference;

		Feedback = in_ros_data.feedback;

		FeedbackDot = in_ros_data.feedback_dot;

		Error = in_ros_data.error;

		ErrorDot = in_ros_data.error_dot;

		TimeStep = in_ros_data.time_step;

		Output = in_ros_data.output;

		
	}

	void SetROS2(control_msgs__msg__SingleDOFState& out_ros_data) const
	{
    	UROS2Utils::StringUEToROS(Name, out_ros_data.name);

		out_ros_data.reference = Reference;

		out_ros_data.feedback = Feedback;

		out_ros_data.feedback_dot = FeedbackDot;

		out_ros_data.error = Error;

		out_ros_data.error_dot = ErrorDot;

		out_ros_data.time_step = TimeStep;

		out_ros_data.output = Output;

		
	}
};

UCLASS()
class RCLUE_API UROS2SingleDOFStateMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSSingleDOFState& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSSingleDOFState& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__SingleDOFState single_dof_state_msg;
};