// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/MotionPrimitiveSequence.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/motion_primitive_sequence.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2MotionPrimitive.h"
#include "control_msgs/msg/detail/motion_primitive__functions.h"


// Generated
#include "ROS2MotionPrimitiveSequence.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSMotionPrimitiveSequence
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FROSMotionPrimitive> Motions;

	

	FROSMotionPrimitiveSequence()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__MotionPrimitiveSequence& in_ros_data)
	{
    	UROS2Utils::SequenceROSToUEArray<control_msgs__msg__MotionPrimitive, FROSMotionPrimitive>(in_ros_data.motions.data, Motions, in_ros_data.motions.size);

		
	}

	void SetROS2(control_msgs__msg__MotionPrimitiveSequence& out_ros_data) const
	{
    	if (out_ros_data.motions.data) {
		control_msgs__msg__MotionPrimitive__Sequence__fini(&out_ros_data.motions);
		}
		if (!control_msgs__msg__MotionPrimitive__Sequence__init(&out_ros_data.motions, Motions.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.motions  "));}
		UROS2Utils::ArrayUEToROSSequence<control_msgs__msg__MotionPrimitive, FROSMotionPrimitive>(Motions, out_ros_data.motions.data, Motions.Num());

		
	}
};

UCLASS()
class RCLUE_API UROS2MotionPrimitiveSequenceMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSMotionPrimitiveSequence& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSMotionPrimitiveSequence& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__MotionPrimitiveSequence motion_primitive_sequence_msg;
};