// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/MecanumDriveControllerState.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/mecanum_drive_controller_state.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"
#include "Msgs/ROS2Twist.h"


// Generated
#include "ROS2MecanumDriveCtrllerState.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSMecanumDriveCtrllerState
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double FrontLeftWheelVelocity = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double BackLeftWheelVelocity = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double BackRightWheelVelocity = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double FrontRightWheelVelocity = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSTwist ReferenceVelocity;

	

	FROSMecanumDriveCtrllerState()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__MecanumDriveControllerState& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		FrontLeftWheelVelocity = in_ros_data.front_left_wheel_velocity;

		BackLeftWheelVelocity = in_ros_data.back_left_wheel_velocity;

		BackRightWheelVelocity = in_ros_data.back_right_wheel_velocity;

		FrontRightWheelVelocity = in_ros_data.front_right_wheel_velocity;

		ReferenceVelocity.SetFromROS2(in_ros_data.reference_velocity);

		
	}

	void SetROS2(control_msgs__msg__MecanumDriveControllerState& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		out_ros_data.front_left_wheel_velocity = FrontLeftWheelVelocity;

		out_ros_data.back_left_wheel_velocity = BackLeftWheelVelocity;

		out_ros_data.back_right_wheel_velocity = BackRightWheelVelocity;

		out_ros_data.front_right_wheel_velocity = FrontRightWheelVelocity;

		ReferenceVelocity.SetROS2(out_ros_data.reference_velocity);

		
	}
};

UCLASS()
class RCLUE_API UROS2MecanumDriveCtrllerStateMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSMecanumDriveCtrllerState& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSMecanumDriveCtrllerState& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__MecanumDriveControllerState mecanum_drive_controller_state_msg;
};