// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/JointJog.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/joint_jog.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"
#include "rosidl_runtime_c/string_functions.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"


// Generated
#include "ROS2JointJog.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSJointJog
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FString> JointNames;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<double> Displacements;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<double> Velocities;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Duration = 0.f;

	

	FROSJointJog()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__JointJog& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		UROS2Utils::StringSequenceROSToUEArray<rosidl_runtime_c__String>(in_ros_data.joint_names.data, JointNames, in_ros_data.joint_names.size);

		UROS2Utils::SequenceROSToUEArray<double, double>(in_ros_data.displacements.data, Displacements, in_ros_data.displacements.size);

		UROS2Utils::SequenceROSToUEArray<double, double>(in_ros_data.velocities.data, Velocities, in_ros_data.velocities.size);

		Duration = in_ros_data.duration;

		
	}

	void SetROS2(control_msgs__msg__JointJog& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		if (out_ros_data.joint_names.data) {
		rosidl_runtime_c__String__Sequence__fini(&out_ros_data.joint_names);
		}
		if (!rosidl_runtime_c__String__Sequence__init(&out_ros_data.joint_names, JointNames.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.joint_names  "));}
		UROS2Utils::StringArrayUEToROSSequence(JointNames, out_ros_data.joint_names.data, JointNames.Num());

		if (out_ros_data.displacements.data) {
		rosidl_runtime_c__float64__Sequence__fini(&out_ros_data.displacements);
		}
		if (!rosidl_runtime_c__float64__Sequence__init(&out_ros_data.displacements, Displacements.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.displacements  "));}
		UROS2Utils::ArrayUEToROSSequence<double, double>(Displacements, out_ros_data.displacements.data, Displacements.Num());

		if (out_ros_data.velocities.data) {
		rosidl_runtime_c__float64__Sequence__fini(&out_ros_data.velocities);
		}
		if (!rosidl_runtime_c__float64__Sequence__init(&out_ros_data.velocities, Velocities.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.velocities  "));}
		UROS2Utils::ArrayUEToROSSequence<double, double>(Velocities, out_ros_data.velocities.data, Velocities.Num());

		out_ros_data.duration = Duration;

		
	}
};

UCLASS()
class RCLUE_API UROS2JointJogMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSJointJog& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSJointJog& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__JointJog joint_jog_msg;
};