// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from clf_audio_msgs/msg/AudioInfo.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "clf_audio_msgs/msg/audio_info.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)


// Generated
#include "ROS2AudioInfo.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSAudioInfo
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	uint8 Channels = 0;

	UPROPERTY(EditAnywhere)
	unsigned int SampleRate = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString SampleFormat;

	UPROPERTY(EditAnywhere)
	unsigned int Bitrate = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString CodingFormat;

	

	FROSAudioInfo()
	{
		
	}

	void SetFromROS2(const clf_audio_msgs__msg__AudioInfo& in_ros_data)
	{
    	Channels = in_ros_data.channels;

		SampleRate = in_ros_data.sample_rate;

		SampleFormat = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.sample_format);

		Bitrate = in_ros_data.bitrate;

		CodingFormat = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.coding_format);

		
	}

	void SetROS2(clf_audio_msgs__msg__AudioInfo& out_ros_data) const
	{
    	out_ros_data.channels = Channels;

		out_ros_data.sample_rate = SampleRate;

		UROS2Utils::StringUEToROS(SampleFormat, out_ros_data.sample_format);

		out_ros_data.bitrate = Bitrate;

		UROS2Utils::StringUEToROS(CodingFormat, out_ros_data.coding_format);

		
	}
};

UCLASS()
class RCLUE_API UROS2AudioInfoMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSAudioInfo& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSAudioInfo& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	clf_audio_msgs__msg__AudioInfo audio_info_msg;
};