// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from clf_ue_audio_msgs/msg/CurrentStatus.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "clf_ue_audio_msgs/msg/current_status.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)


// Generated
#include "ROS2CurrentStatus.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSCurrentStatus
{
	GENERATED_BODY()

public:
		static constexpr int8 TALKING = 0;


	UPROPERTY(EditAnywhere)
	int8 Code = 0;

	

	FROSCurrentStatus()
	{
		
	}

	void SetFromROS2(const clf_ue_audio_msgs__msg__CurrentStatus& in_ros_data)
	{
    	Code = in_ros_data.code;

		
	}

	void SetROS2(clf_ue_audio_msgs__msg__CurrentStatus& out_ros_data) const
	{
    	out_ros_data.code = Code;

		
	}
};

UCLASS()
class RCLUE_API UROS2CurrentStatusMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSCurrentStatus& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSCurrentStatus& Output) const;
	
	virtual void* Get() override;

	static int8 CONST_TALKING()
	{
		return FROSCurrentStatus::TALKING;
	}
	


private:
	virtual FString MsgToString() const override;

	clf_ue_audio_msgs__msg__CurrentStatus current_status_msg;
};