// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/MotionPrimitive.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/msg/motion_primitive.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2MotionArgument.h"
#include "control_msgs/msg/detail/motion_argument__functions.h"
#include "Msgs/ROS2PoseStamped.h"
#include "geometry_msgs/msg/detail/pose_stamped__functions.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"


// Generated
#include "ROS2MotionPrimitive.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSMotionPrimitive
{
	GENERATED_BODY()

public:
		static constexpr int8 UNKNOWN = -1;
	static constexpr int8 LINEAR_JOINT = 0;
	static constexpr int8 LINEAR_CARTESIAN = 50;
	static constexpr int8 CIRCULAR_CARTESIAN = 51;


	UPROPERTY(EditAnywhere)
	int8 Type = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double BlendRadius = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FROSMotionArgument> AdditionalArguments;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FROSPoseStamped> Poses;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<double> JointPositions;

	

	FROSMotionPrimitive()
	{
		
	}

	void SetFromROS2(const control_msgs__msg__MotionPrimitive& in_ros_data)
	{
    	Type = in_ros_data.type;

		BlendRadius = in_ros_data.blend_radius;

		UROS2Utils::SequenceROSToUEArray<control_msgs__msg__MotionArgument, FROSMotionArgument>(in_ros_data.additional_arguments.data, AdditionalArguments, in_ros_data.additional_arguments.size);

		UROS2Utils::SequenceROSToUEArray<geometry_msgs__msg__PoseStamped, FROSPoseStamped>(in_ros_data.poses.data, Poses, in_ros_data.poses.size);

		UROS2Utils::SequenceROSToUEArray<double, double>(in_ros_data.joint_positions.data, JointPositions, in_ros_data.joint_positions.size);

		
	}

	void SetROS2(control_msgs__msg__MotionPrimitive& out_ros_data) const
	{
    	out_ros_data.type = Type;

		out_ros_data.blend_radius = BlendRadius;

		if (out_ros_data.additional_arguments.data) {
		control_msgs__msg__MotionArgument__Sequence__fini(&out_ros_data.additional_arguments);
		}
		if (!control_msgs__msg__MotionArgument__Sequence__init(&out_ros_data.additional_arguments, AdditionalArguments.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.additional_arguments  "));}
		UROS2Utils::ArrayUEToROSSequence<control_msgs__msg__MotionArgument, FROSMotionArgument>(AdditionalArguments, out_ros_data.additional_arguments.data, AdditionalArguments.Num());

		if (out_ros_data.poses.data) {
		geometry_msgs__msg__PoseStamped__Sequence__fini(&out_ros_data.poses);
		}
		if (!geometry_msgs__msg__PoseStamped__Sequence__init(&out_ros_data.poses, Poses.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.poses  "));}
		UROS2Utils::ArrayUEToROSSequence<geometry_msgs__msg__PoseStamped, FROSPoseStamped>(Poses, out_ros_data.poses.data, Poses.Num());

		if (out_ros_data.joint_positions.data) {
		rosidl_runtime_c__float64__Sequence__fini(&out_ros_data.joint_positions);
		}
		if (!rosidl_runtime_c__float64__Sequence__init(&out_ros_data.joint_positions, JointPositions.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.joint_positions  "));}
		UROS2Utils::ArrayUEToROSSequence<double, double>(JointPositions, out_ros_data.joint_positions.data, JointPositions.Num());

		
	}
};

UCLASS()
class RCLUE_API UROS2MotionPrimitiveMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSMotionPrimitive& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSMotionPrimitive& Output) const;
	
	virtual void* Get() override;

	static int8 CONST_UNKNOWN()
	{
		return FROSMotionPrimitive::UNKNOWN;
	}
	static int8 CONST_LINEAR_JOINT()
	{
		return FROSMotionPrimitive::LINEAR_JOINT;
	}
	static int8 CONST_LINEAR_CARTESIAN()
	{
		return FROSMotionPrimitive::LINEAR_CARTESIAN;
	}
	static int8 CONST_CIRCULAR_CARTESIAN()
	{
		return FROSMotionPrimitive::CIRCULAR_CARTESIAN;
	}
	


private:
	virtual FString MsgToString() const override;

	control_msgs__msg__MotionPrimitive motion_primitive_msg;
};