// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/srv/QueryCalibrationState.srv - do not modify

#include "Srvs/ROS2QueryCalibrationState.h"





const rosidl_service_type_support_t* UROS2QueryCalibrationStateSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(control_msgs, srv, QueryCalibrationState);
}

void UROS2QueryCalibrationStateSrv::Init()
{
    control_msgs__srv__QueryCalibrationState_Request__init(&QueryCalibrationState_req);
    control_msgs__srv__QueryCalibrationState_Response__init(&QueryCalibrationState_res);
}

void UROS2QueryCalibrationStateSrv::Fini()
{
    control_msgs__srv__QueryCalibrationState_Request__fini(&QueryCalibrationState_req);
    control_msgs__srv__QueryCalibrationState_Response__fini(&QueryCalibrationState_res);
}

void UROS2QueryCalibrationStateSrv::SetRequest(const FROSQueryCalibrationStateReq& Request)
{
    Request.SetROS2(QueryCalibrationState_req);
}

void UROS2QueryCalibrationStateSrv::GetRequest(FROSQueryCalibrationStateReq& Request) const
{
    Request.SetFromROS2(QueryCalibrationState_req);
}

void UROS2QueryCalibrationStateSrv::SetResponse(const FROSQueryCalibrationStateRes& Response)
{
    Response.SetROS2(QueryCalibrationState_res);
}

void UROS2QueryCalibrationStateSrv::GetResponse(FROSQueryCalibrationStateRes& Response) const
{
    Response.SetFromROS2(QueryCalibrationState_res);
}

void* UROS2QueryCalibrationStateSrv::GetRequest()
{
    return &QueryCalibrationState_req;
}

void* UROS2QueryCalibrationStateSrv::GetResponse()
{
    return &QueryCalibrationState_res;
}

FString UROS2QueryCalibrationStateSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}

FString UROS2QueryCalibrationStateSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}