// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/srv/QueryTrajectoryState.srv - do not modify

#include "Srvs/ROS2QueryTrajState.h"





const rosidl_service_type_support_t* UROS2QueryTrajStateSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(control_msgs, srv, QueryTrajectoryState);
}

void UROS2QueryTrajStateSrv::Init()
{
    control_msgs__srv__QueryTrajectoryState_Request__init(&QueryTrajectoryState_req);
    control_msgs__srv__QueryTrajectoryState_Response__init(&QueryTrajectoryState_res);
}

void UROS2QueryTrajStateSrv::Fini()
{
    control_msgs__srv__QueryTrajectoryState_Request__fini(&QueryTrajectoryState_req);
    control_msgs__srv__QueryTrajectoryState_Response__fini(&QueryTrajectoryState_res);
}

void UROS2QueryTrajStateSrv::SetRequest(const FROSQueryTrajStateReq& Request)
{
    Request.SetROS2(QueryTrajectoryState_req);
}

void UROS2QueryTrajStateSrv::GetRequest(FROSQueryTrajStateReq& Request) const
{
    Request.SetFromROS2(QueryTrajectoryState_req);
}

void UROS2QueryTrajStateSrv::SetResponse(const FROSQueryTrajStateRes& Response)
{
    Response.SetROS2(QueryTrajectoryState_res);
}

void UROS2QueryTrajStateSrv::GetResponse(FROSQueryTrajStateRes& Response) const
{
    Response.SetFromROS2(QueryTrajectoryState_res);
}

void* UROS2QueryTrajStateSrv::GetRequest()
{
    return &QueryTrajectoryState_req;
}

void* UROS2QueryTrajStateSrv::GetResponse()
{
    return &QueryTrajectoryState_res;
}

FString UROS2QueryTrajStateSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}

FString UROS2QueryTrajStateSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}