// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from clf_ue_audio_msgs/action/AudioStreaming.action - do not modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "unique_identifier_msgs/msg/uuid.h"
#include "clf_ue_audio_msgs/action/audio_streaming.h"
#include "action_msgs/srv/cancel_goal.h"

// rclUE
#include "Actions/ROS2GenericAction.h"
#include "rclcUtilities.h"


// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2AudioInfo.h"
#include "Msgs/ROS2AudioData.h"

#include "Msgs/ROS2ReturnCode.h"

#include "Msgs/ROS2CurrentStatus.h"


// Generated
#include "ROS2AudioStreaming.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSAudioStreamingSGReq
{
	GENERATED_BODY()

public:
	

	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSAudioInfo Info;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSAudioData Data;

	

	FROSAudioStreamingSGReq()
    {
        UROS2Utils::GenerateRandomUUID16(GoalId);
		
    }

	void SetFromROS2(const clf_ue_audio_msgs__action__AudioStreaming_SendGoal_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	Info.SetFromROS2(in_ros_data.goal.info);

		Data.SetFromROS2(in_ros_data.goal.data);

		
	}

	void SetROS2(clf_ue_audio_msgs__action__AudioStreaming_SendGoal_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	Info.SetROS2(out_ros_data.goal.info);

		Data.SetROS2(out_ros_data.goal.data);

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSAudioStreamingSGRes
{
	GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bAccepted = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float Stamp = 0.f;

    void SetFromROS2(const clf_ue_audio_msgs__action__AudioStreaming_SendGoal_Response& in_ros_data)
    {
        bAccepted = in_ros_data.accepted;
        Stamp = UROS2Utils::ROSStampToFloat(in_ros_data.stamp);
    }

    void SetROS2(clf_ue_audio_msgs__action__AudioStreaming_SendGoal_Response& out_ros_data) const
    {
        out_ros_data.accepted = bAccepted;
        out_ros_data.stamp = UROS2Utils::FloatToROSStamp(Stamp);
    }
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSAudioStreamingGRReq
{
	GENERATED_BODY()

public:
  	TArray<uint8, TFixedAllocator<16>> GoalId;

    FROSAudioStreamingGRReq()
    {
        GoalId.Init(0, 16);
    }

	void SetFromROS2(const clf_ue_audio_msgs__action__AudioStreaming_GetResult_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

	}

	void SetROS2(clf_ue_audio_msgs__action__AudioStreaming_GetResult_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSAudioStreamingGRRes
{
	GENERATED_BODY()

public:
	

	UPROPERTY()
	int8 GRResStatus = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSReturnCode ReturnCode;

	

	FROSAudioStreamingGRRes()
    {
		
    }

	void SetFromROS2(const clf_ue_audio_msgs__action__AudioStreaming_GetResult_Response& in_ros_data)
	{
		GRResStatus = in_ros_data.status;
    	ReturnCode.SetFromROS2(in_ros_data.result.return_code);

		
	}

	void SetROS2(clf_ue_audio_msgs__action__AudioStreaming_GetResult_Response& out_ros_data) const
	{
		out_ros_data.status = GRResStatus;
    	ReturnCode.SetROS2(out_ros_data.result.return_code);

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSAudioStreamingFB
{
	GENERATED_BODY()

public:
	

  	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSCurrentStatus Status;

	


    FROSAudioStreamingFB()
    {
        GoalId.Init(0, 16);
		
    }

	void SetFromROS2(const clf_ue_audio_msgs__action__AudioStreaming_FeedbackMessage& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	Status.SetFromROS2(in_ros_data.feedback.status);

		
	}

	void SetROS2(clf_ue_audio_msgs__action__AudioStreaming_FeedbackMessage& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	Status.SetROS2(out_ros_data.feedback.status);

		
	}
};

UCLASS()
class RCLUE_API UROS2AudioStreamingAction : public UROS2GenericAction
{
	GENERATED_BODY()

public:
	virtual void Init() override;

	virtual void Fini() override;

	virtual const rosidl_action_type_support_t* GetTypeSupport() const override;

  	UFUNCTION(BlueprintCallable)
	void SetGoalRequest(const FROSAudioStreamingSGReq& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalRequest(FROSAudioStreamingSGReq& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalResponse(const FROSAudioStreamingSGRes& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalResponse(FROSAudioStreamingSGRes& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetResultRequest(const FROSAudioStreamingGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultRequest(FROSAudioStreamingGRReq& Result) const;

    UFUNCTION(BlueprintCallable)
    void SetGoalIdToResultRequest(FROSAudioStreamingGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void SetResultResponse(const FROSAudioStreamingGRRes& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultResponse(FROSAudioStreamingGRRes& Result) const;

  	UFUNCTION(BlueprintCallable)
	void SetFeedback(const FROSAudioStreamingFB& Feedback);

  	UFUNCTION(BlueprintCallable)
	void GetFeedback(FROSAudioStreamingFB& Feedback) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalIdToFeedback(FROSAudioStreamingFB& Feedback);

	virtual void* GetGoalRequest() override;
	virtual void* GetGoalResponse() override;
	virtual void* GetResultRequest() override;
	virtual void* GetResultResponse() override;
	virtual void* GetFeedbackMessage() override;

	
	
	

private:
	clf_ue_audio_msgs__action__AudioStreaming_SendGoal_Request AudioStreaming_goal_request;
	clf_ue_audio_msgs__action__AudioStreaming_SendGoal_Response AudioStreaming_goal_response;
	clf_ue_audio_msgs__action__AudioStreaming_GetResult_Request AudioStreaming_result_request;
	clf_ue_audio_msgs__action__AudioStreaming_GetResult_Response AudioStreaming_result_response;
	clf_ue_audio_msgs__action__AudioStreaming_FeedbackMessage AudioStreaming_feedback_message;
};