// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/action/JointTrajectory.action - do not modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "unique_identifier_msgs/msg/uuid.h"
#include "control_msgs/action/joint_trajectory.h"
#include "action_msgs/srv/cancel_goal.h"

// rclUE
#include "Actions/ROS2GenericAction.h"
#include "rclcUtilities.h"


// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2JointTraj.h"




// Generated
#include "ROS2JointTrajAc.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSJointTrajSGReq
{
	GENERATED_BODY()

public:
	

	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSJointTraj Trajectory;

	

	FROSJointTrajSGReq()
    {
        UROS2Utils::GenerateRandomUUID16(GoalId);
		
    }

	void SetFromROS2(const control_msgs__action__JointTrajectory_SendGoal_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	Trajectory.SetFromROS2(in_ros_data.goal.trajectory);

		
	}

	void SetROS2(control_msgs__action__JointTrajectory_SendGoal_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	Trajectory.SetROS2(out_ros_data.goal.trajectory);

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSJointTrajSGRes
{
	GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bAccepted = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float Stamp = 0.f;

    void SetFromROS2(const control_msgs__action__JointTrajectory_SendGoal_Response& in_ros_data)
    {
        bAccepted = in_ros_data.accepted;
        Stamp = UROS2Utils::ROSStampToFloat(in_ros_data.stamp);
    }

    void SetROS2(control_msgs__action__JointTrajectory_SendGoal_Response& out_ros_data) const
    {
        out_ros_data.accepted = bAccepted;
        out_ros_data.stamp = UROS2Utils::FloatToROSStamp(Stamp);
    }
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSJointTrajGRReq
{
	GENERATED_BODY()

public:
  	TArray<uint8, TFixedAllocator<16>> GoalId;

    FROSJointTrajGRReq()
    {
        GoalId.Init(0, 16);
    }

	void SetFromROS2(const control_msgs__action__JointTrajectory_GetResult_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

	}

	void SetROS2(control_msgs__action__JointTrajectory_GetResult_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSJointTrajGRRes
{
	GENERATED_BODY()

public:
	

	UPROPERTY()
	int8 GRResStatus = 0;

	

	FROSJointTrajGRRes()
    {
		
    }

	void SetFromROS2(const control_msgs__action__JointTrajectory_GetResult_Response& in_ros_data)
	{
		GRResStatus = in_ros_data.status;
    	
	}

	void SetROS2(control_msgs__action__JointTrajectory_GetResult_Response& out_ros_data) const
	{
		out_ros_data.status = GRResStatus;
    	
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSJointTrajFB
{
	GENERATED_BODY()

public:
	

  	TArray<uint8, TFixedAllocator<16>> GoalId;

	


    FROSJointTrajFB()
    {
        GoalId.Init(0, 16);
		
    }

	void SetFromROS2(const control_msgs__action__JointTrajectory_FeedbackMessage& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	
	}

	void SetROS2(control_msgs__action__JointTrajectory_FeedbackMessage& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	
	}
};

UCLASS()
class RCLUE_API UROS2JointTrajAction : public UROS2GenericAction
{
	GENERATED_BODY()

public:
	virtual void Init() override;

	virtual void Fini() override;

	virtual const rosidl_action_type_support_t* GetTypeSupport() const override;

  	UFUNCTION(BlueprintCallable)
	void SetGoalRequest(const FROSJointTrajSGReq& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalRequest(FROSJointTrajSGReq& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalResponse(const FROSJointTrajSGRes& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalResponse(FROSJointTrajSGRes& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetResultRequest(const FROSJointTrajGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultRequest(FROSJointTrajGRReq& Result) const;

    UFUNCTION(BlueprintCallable)
    void SetGoalIdToResultRequest(FROSJointTrajGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void SetResultResponse(const FROSJointTrajGRRes& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultResponse(FROSJointTrajGRRes& Result) const;

  	UFUNCTION(BlueprintCallable)
	void SetFeedback(const FROSJointTrajFB& Feedback);

  	UFUNCTION(BlueprintCallable)
	void GetFeedback(FROSJointTrajFB& Feedback) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalIdToFeedback(FROSJointTrajFB& Feedback);

	virtual void* GetGoalRequest() override;
	virtual void* GetGoalResponse() override;
	virtual void* GetResultRequest() override;
	virtual void* GetResultResponse() override;
	virtual void* GetFeedbackMessage() override;

	
	
	

private:
	control_msgs__action__JointTrajectory_SendGoal_Request JointTrajectory_goal_request;
	control_msgs__action__JointTrajectory_SendGoal_Response JointTrajectory_goal_response;
	control_msgs__action__JointTrajectory_GetResult_Request JointTrajectory_result_request;
	control_msgs__action__JointTrajectory_GetResult_Response JointTrajectory_result_response;
	control_msgs__action__JointTrajectory_FeedbackMessage JointTrajectory_feedback_message;
};