// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/action/FollowJointTrajectory.action - do not modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "unique_identifier_msgs/msg/uuid.h"
#include "control_msgs/action/follow_joint_trajectory.h"
#include "action_msgs/srv/cancel_goal.h"

// rclUE
#include "Actions/ROS2GenericAction.h"
#include "rclcUtilities.h"


// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2JointTraj.h"
#include "Msgs/ROS2MultiDOFJointTraj.h"
#include "Msgs/ROS2JointTolerance.h"
#include "control_msgs/msg/detail/joint_tolerance__functions.h"
#include "Msgs/ROS2JointComponentTolerance.h"
#include "control_msgs/msg/detail/joint_component_tolerance__functions.h"
#include "Msgs/ROS2JointTolerance.h"
#include "control_msgs/msg/detail/joint_tolerance__functions.h"
#include "Msgs/ROS2JointComponentTolerance.h"
#include "control_msgs/msg/detail/joint_component_tolerance__functions.h"
#include "Msgs/ROS2Duration.h"


#include "Msgs/ROS2Header.h"
#include "rosidl_runtime_c/string_functions.h"
#include "Msgs/ROS2JointTrajPoint.h"
#include "Msgs/ROS2JointTrajPoint.h"
#include "Msgs/ROS2JointTrajPoint.h"
#include "rosidl_runtime_c/string_functions.h"
#include "Msgs/ROS2MultiDOFJointTrajPoint.h"
#include "Msgs/ROS2MultiDOFJointTrajPoint.h"
#include "Msgs/ROS2MultiDOFJointTrajPoint.h"


// Generated
#include "ROS2FollowJointTraj.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSFollowJointTrajSGReq
{
	GENERATED_BODY()

public:
	

	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSJointTraj Trajectory;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSMultiDOFJointTraj MultiDofTrajectory;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FROSJointTolerance> PathTolerance;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FROSJointComponentTolerance> ComponentPathTolerance;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FROSJointTolerance> GoalTolerance;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FROSJointComponentTolerance> ComponentGoalTolerance;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSDuration GoalTimeTolerance;

	

	FROSFollowJointTrajSGReq()
    {
        UROS2Utils::GenerateRandomUUID16(GoalId);
		
    }

	void SetFromROS2(const control_msgs__action__FollowJointTrajectory_SendGoal_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	Trajectory.SetFromROS2(in_ros_data.goal.trajectory);

		MultiDofTrajectory.SetFromROS2(in_ros_data.goal.multi_dof_trajectory);

		UROS2Utils::SequenceROSToUEArray<control_msgs__msg__JointTolerance, FROSJointTolerance>(in_ros_data.goal.path_tolerance.data, PathTolerance, in_ros_data.goal.path_tolerance.size);

		UROS2Utils::SequenceROSToUEArray<control_msgs__msg__JointComponentTolerance, FROSJointComponentTolerance>(in_ros_data.goal.component_path_tolerance.data, ComponentPathTolerance, in_ros_data.goal.component_path_tolerance.size);

		UROS2Utils::SequenceROSToUEArray<control_msgs__msg__JointTolerance, FROSJointTolerance>(in_ros_data.goal.goal_tolerance.data, GoalTolerance, in_ros_data.goal.goal_tolerance.size);

		UROS2Utils::SequenceROSToUEArray<control_msgs__msg__JointComponentTolerance, FROSJointComponentTolerance>(in_ros_data.goal.component_goal_tolerance.data, ComponentGoalTolerance, in_ros_data.goal.component_goal_tolerance.size);

		GoalTimeTolerance.SetFromROS2(in_ros_data.goal.goal_time_tolerance);

		
	}

	void SetROS2(control_msgs__action__FollowJointTrajectory_SendGoal_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	Trajectory.SetROS2(out_ros_data.goal.trajectory);

		MultiDofTrajectory.SetROS2(out_ros_data.goal.multi_dof_trajectory);

		if (out_ros_data.goal.path_tolerance.data) {
		control_msgs__msg__JointTolerance__Sequence__fini(&out_ros_data.goal.path_tolerance);
		}
		if (!control_msgs__msg__JointTolerance__Sequence__init(&out_ros_data.goal.path_tolerance, PathTolerance.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.goal.path_tolerance  "));}
		UROS2Utils::ArrayUEToROSSequence<control_msgs__msg__JointTolerance, FROSJointTolerance>(PathTolerance, out_ros_data.goal.path_tolerance.data, PathTolerance.Num());

		if (out_ros_data.goal.component_path_tolerance.data) {
		control_msgs__msg__JointComponentTolerance__Sequence__fini(&out_ros_data.goal.component_path_tolerance);
		}
		if (!control_msgs__msg__JointComponentTolerance__Sequence__init(&out_ros_data.goal.component_path_tolerance, ComponentPathTolerance.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.goal.component_path_tolerance  "));}
		UROS2Utils::ArrayUEToROSSequence<control_msgs__msg__JointComponentTolerance, FROSJointComponentTolerance>(ComponentPathTolerance, out_ros_data.goal.component_path_tolerance.data, ComponentPathTolerance.Num());

		if (out_ros_data.goal.goal_tolerance.data) {
		control_msgs__msg__JointTolerance__Sequence__fini(&out_ros_data.goal.goal_tolerance);
		}
		if (!control_msgs__msg__JointTolerance__Sequence__init(&out_ros_data.goal.goal_tolerance, GoalTolerance.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.goal.goal_tolerance  "));}
		UROS2Utils::ArrayUEToROSSequence<control_msgs__msg__JointTolerance, FROSJointTolerance>(GoalTolerance, out_ros_data.goal.goal_tolerance.data, GoalTolerance.Num());

		if (out_ros_data.goal.component_goal_tolerance.data) {
		control_msgs__msg__JointComponentTolerance__Sequence__fini(&out_ros_data.goal.component_goal_tolerance);
		}
		if (!control_msgs__msg__JointComponentTolerance__Sequence__init(&out_ros_data.goal.component_goal_tolerance, ComponentGoalTolerance.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.goal.component_goal_tolerance  "));}
		UROS2Utils::ArrayUEToROSSequence<control_msgs__msg__JointComponentTolerance, FROSJointComponentTolerance>(ComponentGoalTolerance, out_ros_data.goal.component_goal_tolerance.data, ComponentGoalTolerance.Num());

		GoalTimeTolerance.SetROS2(out_ros_data.goal.goal_time_tolerance);

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSFollowJointTrajSGRes
{
	GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bAccepted = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float Stamp = 0.f;

    void SetFromROS2(const control_msgs__action__FollowJointTrajectory_SendGoal_Response& in_ros_data)
    {
        bAccepted = in_ros_data.accepted;
        Stamp = UROS2Utils::ROSStampToFloat(in_ros_data.stamp);
    }

    void SetROS2(control_msgs__action__FollowJointTrajectory_SendGoal_Response& out_ros_data) const
    {
        out_ros_data.accepted = bAccepted;
        out_ros_data.stamp = UROS2Utils::FloatToROSStamp(Stamp);
    }
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSFollowJointTrajGRReq
{
	GENERATED_BODY()

public:
  	TArray<uint8, TFixedAllocator<16>> GoalId;

    FROSFollowJointTrajGRReq()
    {
        GoalId.Init(0, 16);
    }

	void SetFromROS2(const control_msgs__action__FollowJointTrajectory_GetResult_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

	}

	void SetROS2(control_msgs__action__FollowJointTrajectory_GetResult_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSFollowJointTrajGRRes
{
	GENERATED_BODY()

public:
	

	UPROPERTY()
	int8 GRResStatus = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int ErrorCode = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString ErrorString;

	

	FROSFollowJointTrajGRRes()
    {
		
    }

	void SetFromROS2(const control_msgs__action__FollowJointTrajectory_GetResult_Response& in_ros_data)
	{
		GRResStatus = in_ros_data.status;
    	ErrorCode = in_ros_data.result.error_code;

		ErrorString = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.result.error_string);

		
	}

	void SetROS2(control_msgs__action__FollowJointTrajectory_GetResult_Response& out_ros_data) const
	{
		out_ros_data.status = GRResStatus;
    	out_ros_data.result.error_code = ErrorCode;

		UROS2Utils::StringUEToROS(ErrorString, out_ros_data.result.error_string);

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSFollowJointTrajFB
{
	GENERATED_BODY()

public:
		static constexpr int SUCCESSFUL = 0;
	static constexpr int INVALID_GOAL = -1;
	static constexpr int INVALID_JOINTS = -2;
	static constexpr int OLD_HEADER_TIMESTAMP = -3;
	static constexpr int PATH_TOLERANCE_VIOLATED = -4;
	static constexpr int GOAL_TOLERANCE_VIOLATED = -5;


  	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FString> JointNames;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSJointTrajPoint Desired;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSJointTrajPoint Actual;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSJointTrajPoint Error;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FString> MultiDofJointNames;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSMultiDOFJointTrajPoint MultiDofDesired;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSMultiDOFJointTrajPoint MultiDofActual;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSMultiDOFJointTrajPoint MultiDofError;

	


    FROSFollowJointTrajFB()
    {
        GoalId.Init(0, 16);
		
    }

	void SetFromROS2(const control_msgs__action__FollowJointTrajectory_FeedbackMessage& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	Header.SetFromROS2(in_ros_data.feedback.header);

		UROS2Utils::StringSequenceROSToUEArray<rosidl_runtime_c__String>(in_ros_data.feedback.joint_names.data, JointNames, in_ros_data.feedback.joint_names.size);

		Desired.SetFromROS2(in_ros_data.feedback.desired);

		Actual.SetFromROS2(in_ros_data.feedback.actual);

		Error.SetFromROS2(in_ros_data.feedback.error);

		UROS2Utils::StringSequenceROSToUEArray<rosidl_runtime_c__String>(in_ros_data.feedback.multi_dof_joint_names.data, MultiDofJointNames, in_ros_data.feedback.multi_dof_joint_names.size);

		MultiDofDesired.SetFromROS2(in_ros_data.feedback.multi_dof_desired);

		MultiDofActual.SetFromROS2(in_ros_data.feedback.multi_dof_actual);

		MultiDofError.SetFromROS2(in_ros_data.feedback.multi_dof_error);

		
	}

	void SetROS2(control_msgs__action__FollowJointTrajectory_FeedbackMessage& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	Header.SetROS2(out_ros_data.feedback.header);

		if (out_ros_data.feedback.joint_names.data) {
		rosidl_runtime_c__String__Sequence__fini(&out_ros_data.feedback.joint_names);
		}
		if (!rosidl_runtime_c__String__Sequence__init(&out_ros_data.feedback.joint_names, JointNames.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.feedback.joint_names  "));}
		UROS2Utils::StringArrayUEToROSSequence(JointNames, out_ros_data.feedback.joint_names.data, JointNames.Num());

		Desired.SetROS2(out_ros_data.feedback.desired);

		Actual.SetROS2(out_ros_data.feedback.actual);

		Error.SetROS2(out_ros_data.feedback.error);

		if (out_ros_data.feedback.multi_dof_joint_names.data) {
		rosidl_runtime_c__String__Sequence__fini(&out_ros_data.feedback.multi_dof_joint_names);
		}
		if (!rosidl_runtime_c__String__Sequence__init(&out_ros_data.feedback.multi_dof_joint_names, MultiDofJointNames.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.feedback.multi_dof_joint_names  "));}
		UROS2Utils::StringArrayUEToROSSequence(MultiDofJointNames, out_ros_data.feedback.multi_dof_joint_names.data, MultiDofJointNames.Num());

		MultiDofDesired.SetROS2(out_ros_data.feedback.multi_dof_desired);

		MultiDofActual.SetROS2(out_ros_data.feedback.multi_dof_actual);

		MultiDofError.SetROS2(out_ros_data.feedback.multi_dof_error);

		
	}
};

UCLASS()
class RCLUE_API UROS2FollowJointTrajAction : public UROS2GenericAction
{
	GENERATED_BODY()

public:
	virtual void Init() override;

	virtual void Fini() override;

	virtual const rosidl_action_type_support_t* GetTypeSupport() const override;

  	UFUNCTION(BlueprintCallable)
	void SetGoalRequest(const FROSFollowJointTrajSGReq& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalRequest(FROSFollowJointTrajSGReq& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalResponse(const FROSFollowJointTrajSGRes& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalResponse(FROSFollowJointTrajSGRes& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetResultRequest(const FROSFollowJointTrajGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultRequest(FROSFollowJointTrajGRReq& Result) const;

    UFUNCTION(BlueprintCallable)
    void SetGoalIdToResultRequest(FROSFollowJointTrajGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void SetResultResponse(const FROSFollowJointTrajGRRes& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultResponse(FROSFollowJointTrajGRRes& Result) const;

  	UFUNCTION(BlueprintCallable)
	void SetFeedback(const FROSFollowJointTrajFB& Feedback);

  	UFUNCTION(BlueprintCallable)
	void GetFeedback(FROSFollowJointTrajFB& Feedback) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalIdToFeedback(FROSFollowJointTrajFB& Feedback);

	virtual void* GetGoalRequest() override;
	virtual void* GetGoalResponse() override;
	virtual void* GetResultRequest() override;
	virtual void* GetResultResponse() override;
	virtual void* GetFeedbackMessage() override;

	
	
	UFUNCTION(BlueprintCallable)
	static int CONST_SUCCESSFUL()
	{
		return FROSFollowJointTrajFB::SUCCESSFUL;
	}
	UFUNCTION(BlueprintCallable)
	static int CONST_INVALID_GOAL()
	{
		return FROSFollowJointTrajFB::INVALID_GOAL;
	}
	UFUNCTION(BlueprintCallable)
	static int CONST_INVALID_JOINTS()
	{
		return FROSFollowJointTrajFB::INVALID_JOINTS;
	}
	UFUNCTION(BlueprintCallable)
	static int CONST_OLD_HEADER_TIMESTAMP()
	{
		return FROSFollowJointTrajFB::OLD_HEADER_TIMESTAMP;
	}
	UFUNCTION(BlueprintCallable)
	static int CONST_PATH_TOLERANCE_VIOLATED()
	{
		return FROSFollowJointTrajFB::PATH_TOLERANCE_VIOLATED;
	}
	UFUNCTION(BlueprintCallable)
	static int CONST_GOAL_TOLERANCE_VIOLATED()
	{
		return FROSFollowJointTrajFB::GOAL_TOLERANCE_VIOLATED;
	}
	

private:
	control_msgs__action__FollowJointTrajectory_SendGoal_Request FollowJointTrajectory_goal_request;
	control_msgs__action__FollowJointTrajectory_SendGoal_Response FollowJointTrajectory_goal_response;
	control_msgs__action__FollowJointTrajectory_GetResult_Request FollowJointTrajectory_result_request;
	control_msgs__action__FollowJointTrajectory_GetResult_Response FollowJointTrajectory_result_response;
	control_msgs__action__FollowJointTrajectory_FeedbackMessage FollowJointTrajectory_feedback_message;
};