// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/action/SingleJointPosition.action - do not modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "unique_identifier_msgs/msg/uuid.h"
#include "control_msgs/action/single_joint_position.h"
#include "action_msgs/srv/cancel_goal.h"

// rclUE
#include "Actions/ROS2GenericAction.h"
#include "rclcUtilities.h"


// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Duration.h"


#include "Msgs/ROS2Header.h"


// Generated
#include "ROS2SingleJointPosition.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSSingleJointPositionSGReq
{
	GENERATED_BODY()

public:
	

	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Position = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSDuration MinDuration;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double MaxVelocity = 0.f;

	

	FROSSingleJointPositionSGReq()
    {
        UROS2Utils::GenerateRandomUUID16(GoalId);
		
    }

	void SetFromROS2(const control_msgs__action__SingleJointPosition_SendGoal_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	Position = in_ros_data.goal.position;

		MinDuration.SetFromROS2(in_ros_data.goal.min_duration);

		MaxVelocity = in_ros_data.goal.max_velocity;

		
	}

	void SetROS2(control_msgs__action__SingleJointPosition_SendGoal_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	out_ros_data.goal.position = Position;

		MinDuration.SetROS2(out_ros_data.goal.min_duration);

		out_ros_data.goal.max_velocity = MaxVelocity;

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSSingleJointPositionSGRes
{
	GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bAccepted = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float Stamp = 0.f;

    void SetFromROS2(const control_msgs__action__SingleJointPosition_SendGoal_Response& in_ros_data)
    {
        bAccepted = in_ros_data.accepted;
        Stamp = UROS2Utils::ROSStampToFloat(in_ros_data.stamp);
    }

    void SetROS2(control_msgs__action__SingleJointPosition_SendGoal_Response& out_ros_data) const
    {
        out_ros_data.accepted = bAccepted;
        out_ros_data.stamp = UROS2Utils::FloatToROSStamp(Stamp);
    }
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSSingleJointPositionGRReq
{
	GENERATED_BODY()

public:
  	TArray<uint8, TFixedAllocator<16>> GoalId;

    FROSSingleJointPositionGRReq()
    {
        GoalId.Init(0, 16);
    }

	void SetFromROS2(const control_msgs__action__SingleJointPosition_GetResult_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

	}

	void SetROS2(control_msgs__action__SingleJointPosition_GetResult_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSSingleJointPositionGRRes
{
	GENERATED_BODY()

public:
	

	UPROPERTY()
	int8 GRResStatus = 0;

	

	FROSSingleJointPositionGRRes()
    {
		
    }

	void SetFromROS2(const control_msgs__action__SingleJointPosition_GetResult_Response& in_ros_data)
	{
		GRResStatus = in_ros_data.status;
    	
	}

	void SetROS2(control_msgs__action__SingleJointPosition_GetResult_Response& out_ros_data) const
	{
		out_ros_data.status = GRResStatus;
    	
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSSingleJointPositionFB
{
	GENERATED_BODY()

public:
	

  	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Position = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Velocity = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Error = 0.f;

	


    FROSSingleJointPositionFB()
    {
        GoalId.Init(0, 16);
		
    }

	void SetFromROS2(const control_msgs__action__SingleJointPosition_FeedbackMessage& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	Header.SetFromROS2(in_ros_data.feedback.header);

		Position = in_ros_data.feedback.position;

		Velocity = in_ros_data.feedback.velocity;

		Error = in_ros_data.feedback.error;

		
	}

	void SetROS2(control_msgs__action__SingleJointPosition_FeedbackMessage& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	Header.SetROS2(out_ros_data.feedback.header);

		out_ros_data.feedback.position = Position;

		out_ros_data.feedback.velocity = Velocity;

		out_ros_data.feedback.error = Error;

		
	}
};

UCLASS()
class RCLUE_API UROS2SingleJointPositionAction : public UROS2GenericAction
{
	GENERATED_BODY()

public:
	virtual void Init() override;

	virtual void Fini() override;

	virtual const rosidl_action_type_support_t* GetTypeSupport() const override;

  	UFUNCTION(BlueprintCallable)
	void SetGoalRequest(const FROSSingleJointPositionSGReq& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalRequest(FROSSingleJointPositionSGReq& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalResponse(const FROSSingleJointPositionSGRes& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalResponse(FROSSingleJointPositionSGRes& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetResultRequest(const FROSSingleJointPositionGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultRequest(FROSSingleJointPositionGRReq& Result) const;

    UFUNCTION(BlueprintCallable)
    void SetGoalIdToResultRequest(FROSSingleJointPositionGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void SetResultResponse(const FROSSingleJointPositionGRRes& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultResponse(FROSSingleJointPositionGRRes& Result) const;

  	UFUNCTION(BlueprintCallable)
	void SetFeedback(const FROSSingleJointPositionFB& Feedback);

  	UFUNCTION(BlueprintCallable)
	void GetFeedback(FROSSingleJointPositionFB& Feedback) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalIdToFeedback(FROSSingleJointPositionFB& Feedback);

	virtual void* GetGoalRequest() override;
	virtual void* GetGoalResponse() override;
	virtual void* GetResultRequest() override;
	virtual void* GetResultResponse() override;
	virtual void* GetFeedbackMessage() override;

	
	
	

private:
	control_msgs__action__SingleJointPosition_SendGoal_Request SingleJointPosition_goal_request;
	control_msgs__action__SingleJointPosition_SendGoal_Response SingleJointPosition_goal_response;
	control_msgs__action__SingleJointPosition_GetResult_Request SingleJointPosition_result_request;
	control_msgs__action__SingleJointPosition_GetResult_Response SingleJointPosition_result_response;
	control_msgs__action__SingleJointPosition_FeedbackMessage SingleJointPosition_feedback_message;
};