// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/action/ParallelGripperCommand.action - do not modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "unique_identifier_msgs/msg/uuid.h"
#include "control_msgs/action/parallel_gripper_command.h"
#include "action_msgs/srv/cancel_goal.h"

// rclUE
#include "Actions/ROS2GenericAction.h"
#include "rclcUtilities.h"


// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2JointState.h"

#include "Msgs/ROS2JointState.h"

#include "Msgs/ROS2JointState.h"


// Generated
#include "ROS2ParallelGripperCommand.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSParallelGripperCommandSGReq
{
	GENERATED_BODY()

public:
	

	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSJointState Command;

	

	FROSParallelGripperCommandSGReq()
    {
        UROS2Utils::GenerateRandomUUID16(GoalId);
		
    }

	void SetFromROS2(const control_msgs__action__ParallelGripperCommand_SendGoal_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	Command.SetFromROS2(in_ros_data.goal.command);

		
	}

	void SetROS2(control_msgs__action__ParallelGripperCommand_SendGoal_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	Command.SetROS2(out_ros_data.goal.command);

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSParallelGripperCommandSGRes
{
	GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bAccepted = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float Stamp = 0.f;

    void SetFromROS2(const control_msgs__action__ParallelGripperCommand_SendGoal_Response& in_ros_data)
    {
        bAccepted = in_ros_data.accepted;
        Stamp = UROS2Utils::ROSStampToFloat(in_ros_data.stamp);
    }

    void SetROS2(control_msgs__action__ParallelGripperCommand_SendGoal_Response& out_ros_data) const
    {
        out_ros_data.accepted = bAccepted;
        out_ros_data.stamp = UROS2Utils::FloatToROSStamp(Stamp);
    }
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSParallelGripperCommandGRReq
{
	GENERATED_BODY()

public:
  	TArray<uint8, TFixedAllocator<16>> GoalId;

    FROSParallelGripperCommandGRReq()
    {
        GoalId.Init(0, 16);
    }

	void SetFromROS2(const control_msgs__action__ParallelGripperCommand_GetResult_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

	}

	void SetROS2(control_msgs__action__ParallelGripperCommand_GetResult_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSParallelGripperCommandGRRes
{
	GENERATED_BODY()

public:
	

	UPROPERTY()
	int8 GRResStatus = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSJointState State;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bStalled = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bReachedGoal = false;

	

	FROSParallelGripperCommandGRRes()
    {
		
    }

	void SetFromROS2(const control_msgs__action__ParallelGripperCommand_GetResult_Response& in_ros_data)
	{
		GRResStatus = in_ros_data.status;
    	State.SetFromROS2(in_ros_data.result.state);

		bStalled = in_ros_data.result.stalled;

		bReachedGoal = in_ros_data.result.reached_goal;

		
	}

	void SetROS2(control_msgs__action__ParallelGripperCommand_GetResult_Response& out_ros_data) const
	{
		out_ros_data.status = GRResStatus;
    	State.SetROS2(out_ros_data.result.state);

		out_ros_data.result.stalled = bStalled;

		out_ros_data.result.reached_goal = bReachedGoal;

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSParallelGripperCommandFB
{
	GENERATED_BODY()

public:
	

  	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSJointState State;

	


    FROSParallelGripperCommandFB()
    {
        GoalId.Init(0, 16);
		
    }

	void SetFromROS2(const control_msgs__action__ParallelGripperCommand_FeedbackMessage& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	State.SetFromROS2(in_ros_data.feedback.state);

		
	}

	void SetROS2(control_msgs__action__ParallelGripperCommand_FeedbackMessage& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	State.SetROS2(out_ros_data.feedback.state);

		
	}
};

UCLASS()
class RCLUE_API UROS2ParallelGripperCommandAction : public UROS2GenericAction
{
	GENERATED_BODY()

public:
	virtual void Init() override;

	virtual void Fini() override;

	virtual const rosidl_action_type_support_t* GetTypeSupport() const override;

  	UFUNCTION(BlueprintCallable)
	void SetGoalRequest(const FROSParallelGripperCommandSGReq& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalRequest(FROSParallelGripperCommandSGReq& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalResponse(const FROSParallelGripperCommandSGRes& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalResponse(FROSParallelGripperCommandSGRes& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetResultRequest(const FROSParallelGripperCommandGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultRequest(FROSParallelGripperCommandGRReq& Result) const;

    UFUNCTION(BlueprintCallable)
    void SetGoalIdToResultRequest(FROSParallelGripperCommandGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void SetResultResponse(const FROSParallelGripperCommandGRRes& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultResponse(FROSParallelGripperCommandGRRes& Result) const;

  	UFUNCTION(BlueprintCallable)
	void SetFeedback(const FROSParallelGripperCommandFB& Feedback);

  	UFUNCTION(BlueprintCallable)
	void GetFeedback(FROSParallelGripperCommandFB& Feedback) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalIdToFeedback(FROSParallelGripperCommandFB& Feedback);

	virtual void* GetGoalRequest() override;
	virtual void* GetGoalResponse() override;
	virtual void* GetResultRequest() override;
	virtual void* GetResultResponse() override;
	virtual void* GetFeedbackMessage() override;

	
	
	

private:
	control_msgs__action__ParallelGripperCommand_SendGoal_Request ParallelGripperCommand_goal_request;
	control_msgs__action__ParallelGripperCommand_SendGoal_Response ParallelGripperCommand_goal_response;
	control_msgs__action__ParallelGripperCommand_GetResult_Request ParallelGripperCommand_result_request;
	control_msgs__action__ParallelGripperCommand_GetResult_Response ParallelGripperCommand_result_response;
	control_msgs__action__ParallelGripperCommand_FeedbackMessage ParallelGripperCommand_feedback_message;
};