// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/action/ExecuteMotionPrimitiveSequence.action - do not modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "unique_identifier_msgs/msg/uuid.h"
#include "control_msgs/action/execute_motion_primitive_sequence.h"
#include "action_msgs/srv/cancel_goal.h"

// rclUE
#include "Actions/ROS2GenericAction.h"
#include "rclcUtilities.h"


// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2MotionPrimitiveSequence.h"




// Generated
#include "ROS2ExecuteMotionPrimitiveSequence.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSExecuteMotionPrimitiveSequenceSGReq
{
	GENERATED_BODY()

public:
	

	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSMotionPrimitiveSequence Trajectory;

	

	FROSExecuteMotionPrimitiveSequenceSGReq()
    {
        UROS2Utils::GenerateRandomUUID16(GoalId);
		
    }

	void SetFromROS2(const control_msgs__action__ExecuteMotionPrimitiveSequence_SendGoal_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	Trajectory.SetFromROS2(in_ros_data.goal.trajectory);

		
	}

	void SetROS2(control_msgs__action__ExecuteMotionPrimitiveSequence_SendGoal_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	Trajectory.SetROS2(out_ros_data.goal.trajectory);

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSExecuteMotionPrimitiveSequenceSGRes
{
	GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bAccepted = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float Stamp = 0.f;

    void SetFromROS2(const control_msgs__action__ExecuteMotionPrimitiveSequence_SendGoal_Response& in_ros_data)
    {
        bAccepted = in_ros_data.accepted;
        Stamp = UROS2Utils::ROSStampToFloat(in_ros_data.stamp);
    }

    void SetROS2(control_msgs__action__ExecuteMotionPrimitiveSequence_SendGoal_Response& out_ros_data) const
    {
        out_ros_data.accepted = bAccepted;
        out_ros_data.stamp = UROS2Utils::FloatToROSStamp(Stamp);
    }
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSExecuteMotionPrimitiveSequenceGRReq
{
	GENERATED_BODY()

public:
  	TArray<uint8, TFixedAllocator<16>> GoalId;

    FROSExecuteMotionPrimitiveSequenceGRReq()
    {
        GoalId.Init(0, 16);
    }

	void SetFromROS2(const control_msgs__action__ExecuteMotionPrimitiveSequence_GetResult_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

	}

	void SetROS2(control_msgs__action__ExecuteMotionPrimitiveSequence_GetResult_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSExecuteMotionPrimitiveSequenceGRRes
{
	GENERATED_BODY()

public:
	

	UPROPERTY()
	int8 GRResStatus = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int ErrorCode = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString ErrorString;

	

	FROSExecuteMotionPrimitiveSequenceGRRes()
    {
		
    }

	void SetFromROS2(const control_msgs__action__ExecuteMotionPrimitiveSequence_GetResult_Response& in_ros_data)
	{
		GRResStatus = in_ros_data.status;
    	ErrorCode = in_ros_data.result.error_code;

		ErrorString = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.result.error_string);

		
	}

	void SetROS2(control_msgs__action__ExecuteMotionPrimitiveSequence_GetResult_Response& out_ros_data) const
	{
		out_ros_data.status = GRResStatus;
    	out_ros_data.result.error_code = ErrorCode;

		UROS2Utils::StringUEToROS(ErrorString, out_ros_data.result.error_string);

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSExecuteMotionPrimitiveSequenceFB
{
	GENERATED_BODY()

public:
		static constexpr int SUCCESSFUL = 0;
	static constexpr int INVALID_GOAL = -1;
	static constexpr int OLD_HEADER_TIMESTAMP = -3;


  	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	uint8 CurrentPrimitiveIndex = 0;

	


    FROSExecuteMotionPrimitiveSequenceFB()
    {
        GoalId.Init(0, 16);
		
    }

	void SetFromROS2(const control_msgs__action__ExecuteMotionPrimitiveSequence_FeedbackMessage& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	CurrentPrimitiveIndex = in_ros_data.feedback.current_primitive_index;

		
	}

	void SetROS2(control_msgs__action__ExecuteMotionPrimitiveSequence_FeedbackMessage& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	out_ros_data.feedback.current_primitive_index = CurrentPrimitiveIndex;

		
	}
};

UCLASS()
class RCLUE_API UROS2ExecuteMotionPrimitiveSequenceAction : public UROS2GenericAction
{
	GENERATED_BODY()

public:
	virtual void Init() override;

	virtual void Fini() override;

	virtual const rosidl_action_type_support_t* GetTypeSupport() const override;

  	UFUNCTION(BlueprintCallable)
	void SetGoalRequest(const FROSExecuteMotionPrimitiveSequenceSGReq& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalRequest(FROSExecuteMotionPrimitiveSequenceSGReq& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalResponse(const FROSExecuteMotionPrimitiveSequenceSGRes& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalResponse(FROSExecuteMotionPrimitiveSequenceSGRes& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetResultRequest(const FROSExecuteMotionPrimitiveSequenceGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultRequest(FROSExecuteMotionPrimitiveSequenceGRReq& Result) const;

    UFUNCTION(BlueprintCallable)
    void SetGoalIdToResultRequest(FROSExecuteMotionPrimitiveSequenceGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void SetResultResponse(const FROSExecuteMotionPrimitiveSequenceGRRes& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultResponse(FROSExecuteMotionPrimitiveSequenceGRRes& Result) const;

  	UFUNCTION(BlueprintCallable)
	void SetFeedback(const FROSExecuteMotionPrimitiveSequenceFB& Feedback);

  	UFUNCTION(BlueprintCallable)
	void GetFeedback(FROSExecuteMotionPrimitiveSequenceFB& Feedback) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalIdToFeedback(FROSExecuteMotionPrimitiveSequenceFB& Feedback);

	virtual void* GetGoalRequest() override;
	virtual void* GetGoalResponse() override;
	virtual void* GetResultRequest() override;
	virtual void* GetResultResponse() override;
	virtual void* GetFeedbackMessage() override;

	
	
	UFUNCTION(BlueprintCallable)
	static int CONST_SUCCESSFUL()
	{
		return FROSExecuteMotionPrimitiveSequenceFB::SUCCESSFUL;
	}
	UFUNCTION(BlueprintCallable)
	static int CONST_INVALID_GOAL()
	{
		return FROSExecuteMotionPrimitiveSequenceFB::INVALID_GOAL;
	}
	UFUNCTION(BlueprintCallable)
	static int CONST_OLD_HEADER_TIMESTAMP()
	{
		return FROSExecuteMotionPrimitiveSequenceFB::OLD_HEADER_TIMESTAMP;
	}
	

private:
	control_msgs__action__ExecuteMotionPrimitiveSequence_SendGoal_Request ExecuteMotionPrimitiveSequence_goal_request;
	control_msgs__action__ExecuteMotionPrimitiveSequence_SendGoal_Response ExecuteMotionPrimitiveSequence_goal_response;
	control_msgs__action__ExecuteMotionPrimitiveSequence_GetResult_Request ExecuteMotionPrimitiveSequence_result_request;
	control_msgs__action__ExecuteMotionPrimitiveSequence_GetResult_Response ExecuteMotionPrimitiveSequence_result_response;
	control_msgs__action__ExecuteMotionPrimitiveSequence_FeedbackMessage ExecuteMotionPrimitiveSequence_feedback_message;
};