// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/action/PointHead.action - do not modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "unique_identifier_msgs/msg/uuid.h"
#include "control_msgs/action/point_head.h"
#include "action_msgs/srv/cancel_goal.h"

// rclUE
#include "Actions/ROS2GenericAction.h"
#include "rclcUtilities.h"


// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2PointStamped.h"
#include "Msgs/ROS2Duration.h"




// Generated
#include "ROS2PointHead.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSPointHeadSGReq
{
	GENERATED_BODY()

public:
	

	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSPointStamped Target;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector PointingAxis = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString PointingFrame;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSDuration MinDuration;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double MaxVelocity = 0.f;

	

	FROSPointHeadSGReq()
    {
        UROS2Utils::GenerateRandomUUID16(GoalId);
		
    }

	void SetFromROS2(const control_msgs__action__PointHead_SendGoal_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	Target.SetFromROS2(in_ros_data.goal.target);

		PointingAxis = UROS2Utils::VectorROSToUE<geometry_msgs__msg__Vector3>(in_ros_data.goal.pointing_axis);

		PointingFrame = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.goal.pointing_frame);

		MinDuration.SetFromROS2(in_ros_data.goal.min_duration);

		MaxVelocity = in_ros_data.goal.max_velocity;

		
	}

	void SetROS2(control_msgs__action__PointHead_SendGoal_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	Target.SetROS2(out_ros_data.goal.target);

		out_ros_data.goal.pointing_axis = UROS2Utils::VectorUEToROS<geometry_msgs__msg__Vector3>(PointingAxis);

		UROS2Utils::StringUEToROS(PointingFrame, out_ros_data.goal.pointing_frame);

		MinDuration.SetROS2(out_ros_data.goal.min_duration);

		out_ros_data.goal.max_velocity = MaxVelocity;

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSPointHeadSGRes
{
	GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bAccepted = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float Stamp = 0.f;

    void SetFromROS2(const control_msgs__action__PointHead_SendGoal_Response& in_ros_data)
    {
        bAccepted = in_ros_data.accepted;
        Stamp = UROS2Utils::ROSStampToFloat(in_ros_data.stamp);
    }

    void SetROS2(control_msgs__action__PointHead_SendGoal_Response& out_ros_data) const
    {
        out_ros_data.accepted = bAccepted;
        out_ros_data.stamp = UROS2Utils::FloatToROSStamp(Stamp);
    }
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSPointHeadGRReq
{
	GENERATED_BODY()

public:
  	TArray<uint8, TFixedAllocator<16>> GoalId;

    FROSPointHeadGRReq()
    {
        GoalId.Init(0, 16);
    }

	void SetFromROS2(const control_msgs__action__PointHead_GetResult_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

	}

	void SetROS2(control_msgs__action__PointHead_GetResult_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSPointHeadGRRes
{
	GENERATED_BODY()

public:
	

	UPROPERTY()
	int8 GRResStatus = 0;

	

	FROSPointHeadGRRes()
    {
		
    }

	void SetFromROS2(const control_msgs__action__PointHead_GetResult_Response& in_ros_data)
	{
		GRResStatus = in_ros_data.status;
    	
	}

	void SetROS2(control_msgs__action__PointHead_GetResult_Response& out_ros_data) const
	{
		out_ros_data.status = GRResStatus;
    	
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSPointHeadFB
{
	GENERATED_BODY()

public:
	

  	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double PointingAngleError = 0.f;

	


    FROSPointHeadFB()
    {
        GoalId.Init(0, 16);
		
    }

	void SetFromROS2(const control_msgs__action__PointHead_FeedbackMessage& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	PointingAngleError = in_ros_data.feedback.pointing_angle_error;

		
	}

	void SetROS2(control_msgs__action__PointHead_FeedbackMessage& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	out_ros_data.feedback.pointing_angle_error = PointingAngleError;

		
	}
};

UCLASS()
class RCLUE_API UROS2PointHeadAction : public UROS2GenericAction
{
	GENERATED_BODY()

public:
	virtual void Init() override;

	virtual void Fini() override;

	virtual const rosidl_action_type_support_t* GetTypeSupport() const override;

  	UFUNCTION(BlueprintCallable)
	void SetGoalRequest(const FROSPointHeadSGReq& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalRequest(FROSPointHeadSGReq& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalResponse(const FROSPointHeadSGRes& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalResponse(FROSPointHeadSGRes& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetResultRequest(const FROSPointHeadGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultRequest(FROSPointHeadGRReq& Result) const;

    UFUNCTION(BlueprintCallable)
    void SetGoalIdToResultRequest(FROSPointHeadGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void SetResultResponse(const FROSPointHeadGRRes& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultResponse(FROSPointHeadGRRes& Result) const;

  	UFUNCTION(BlueprintCallable)
	void SetFeedback(const FROSPointHeadFB& Feedback);

  	UFUNCTION(BlueprintCallable)
	void GetFeedback(FROSPointHeadFB& Feedback) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalIdToFeedback(FROSPointHeadFB& Feedback);

	virtual void* GetGoalRequest() override;
	virtual void* GetGoalResponse() override;
	virtual void* GetResultRequest() override;
	virtual void* GetResultResponse() override;
	virtual void* GetFeedbackMessage() override;

	
	
	

private:
	control_msgs__action__PointHead_SendGoal_Request PointHead_goal_request;
	control_msgs__action__PointHead_SendGoal_Response PointHead_goal_response;
	control_msgs__action__PointHead_GetResult_Request PointHead_result_request;
	control_msgs__action__PointHead_GetResult_Response PointHead_result_response;
	control_msgs__action__PointHead_FeedbackMessage PointHead_feedback_message;
};