// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/action/GripperCommand.action - do not modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "unique_identifier_msgs/msg/uuid.h"
#include "control_msgs/action/gripper_command.h"
#include "action_msgs/srv/cancel_goal.h"

// rclUE
#include "Actions/ROS2GenericAction.h"
#include "rclcUtilities.h"


// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2GripperCommand.h"




// Generated
#include "ROS2GripperCommandAc.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSGripperCommandSGReq
{
	GENERATED_BODY()

public:
	

	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSGripperCommand Command;

	

	FROSGripperCommandSGReq()
    {
        UROS2Utils::GenerateRandomUUID16(GoalId);
		
    }

	void SetFromROS2(const control_msgs__action__GripperCommand_SendGoal_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	Command.SetFromROS2(in_ros_data.goal.command);

		
	}

	void SetROS2(control_msgs__action__GripperCommand_SendGoal_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	Command.SetROS2(out_ros_data.goal.command);

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSGripperCommandSGRes
{
	GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bAccepted = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float Stamp = 0.f;

    void SetFromROS2(const control_msgs__action__GripperCommand_SendGoal_Response& in_ros_data)
    {
        bAccepted = in_ros_data.accepted;
        Stamp = UROS2Utils::ROSStampToFloat(in_ros_data.stamp);
    }

    void SetROS2(control_msgs__action__GripperCommand_SendGoal_Response& out_ros_data) const
    {
        out_ros_data.accepted = bAccepted;
        out_ros_data.stamp = UROS2Utils::FloatToROSStamp(Stamp);
    }
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSGripperCommandGRReq
{
	GENERATED_BODY()

public:
  	TArray<uint8, TFixedAllocator<16>> GoalId;

    FROSGripperCommandGRReq()
    {
        GoalId.Init(0, 16);
    }

	void SetFromROS2(const control_msgs__action__GripperCommand_GetResult_Request& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

	}

	void SetROS2(control_msgs__action__GripperCommand_GetResult_Request& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSGripperCommandGRRes
{
	GENERATED_BODY()

public:
	

	UPROPERTY()
	int8 GRResStatus = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Position = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Effort = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bStalled = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bReachedGoal = false;

	

	FROSGripperCommandGRRes()
    {
		
    }

	void SetFromROS2(const control_msgs__action__GripperCommand_GetResult_Response& in_ros_data)
	{
		GRResStatus = in_ros_data.status;
    	Position = in_ros_data.result.position;

		Effort = in_ros_data.result.effort;

		bStalled = in_ros_data.result.stalled;

		bReachedGoal = in_ros_data.result.reached_goal;

		
	}

	void SetROS2(control_msgs__action__GripperCommand_GetResult_Response& out_ros_data) const
	{
		out_ros_data.status = GRResStatus;
    	out_ros_data.result.position = Position;

		out_ros_data.result.effort = Effort;

		out_ros_data.result.stalled = bStalled;

		out_ros_data.result.reached_goal = bReachedGoal;

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSGripperCommandFB
{
	GENERATED_BODY()

public:
	

  	TArray<uint8, TFixedAllocator<16>> GoalId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Position = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Effort = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bStalled = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bReachedGoal = false;

	


    FROSGripperCommandFB()
    {
        GoalId.Init(0, 16);
		
    }

	void SetFromROS2(const control_msgs__action__GripperCommand_FeedbackMessage& in_ros_data)
	{
		for (int i=0; i<16; i++)
		{
			GoalId[i] = in_ros_data.goal_id.uuid[i];
		}

    	Position = in_ros_data.feedback.position;

		Effort = in_ros_data.feedback.effort;

		bStalled = in_ros_data.feedback.stalled;

		bReachedGoal = in_ros_data.feedback.reached_goal;

		
	}

	void SetROS2(control_msgs__action__GripperCommand_FeedbackMessage& out_ros_data) const
	{
		for (int i=0; i<16; i++)
		{
			out_ros_data.goal_id.uuid[i] = GoalId[i];
		}

    	out_ros_data.feedback.position = Position;

		out_ros_data.feedback.effort = Effort;

		out_ros_data.feedback.stalled = bStalled;

		out_ros_data.feedback.reached_goal = bReachedGoal;

		
	}
};

UCLASS()
class RCLUE_API UROS2GripperCommandAction : public UROS2GenericAction
{
	GENERATED_BODY()

public:
	virtual void Init() override;

	virtual void Fini() override;

	virtual const rosidl_action_type_support_t* GetTypeSupport() const override;

  	UFUNCTION(BlueprintCallable)
	void SetGoalRequest(const FROSGripperCommandSGReq& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalRequest(FROSGripperCommandSGReq& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalResponse(const FROSGripperCommandSGRes& Goal);

  	UFUNCTION(BlueprintCallable)
	void GetGoalResponse(FROSGripperCommandSGRes& Goal) const;

  	UFUNCTION(BlueprintCallable)
	void SetResultRequest(const FROSGripperCommandGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultRequest(FROSGripperCommandGRReq& Result) const;

    UFUNCTION(BlueprintCallable)
    void SetGoalIdToResultRequest(FROSGripperCommandGRReq& Result);

  	UFUNCTION(BlueprintCallable)
	void SetResultResponse(const FROSGripperCommandGRRes& Result);

  	UFUNCTION(BlueprintCallable)
	void GetResultResponse(FROSGripperCommandGRRes& Result) const;

  	UFUNCTION(BlueprintCallable)
	void SetFeedback(const FROSGripperCommandFB& Feedback);

  	UFUNCTION(BlueprintCallable)
	void GetFeedback(FROSGripperCommandFB& Feedback) const;

  	UFUNCTION(BlueprintCallable)
	void SetGoalIdToFeedback(FROSGripperCommandFB& Feedback);

	virtual void* GetGoalRequest() override;
	virtual void* GetGoalResponse() override;
	virtual void* GetResultRequest() override;
	virtual void* GetResultResponse() override;
	virtual void* GetFeedbackMessage() override;

	
	
	

private:
	control_msgs__action__GripperCommand_SendGoal_Request GripperCommand_goal_request;
	control_msgs__action__GripperCommand_SendGoal_Response GripperCommand_goal_response;
	control_msgs__action__GripperCommand_GetResult_Request GripperCommand_result_request;
	control_msgs__action__GripperCommand_GetResult_Response GripperCommand_result_response;
	control_msgs__action__GripperCommand_FeedbackMessage GripperCommand_feedback_message;
};