// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/action/GripperCommand.action - do not modify

#include "Actions/ROS2GripperCommandAc.h"





const rosidl_action_type_support_t* UROS2GripperCommandAction::GetTypeSupport() const
{
    return ROSIDL_GET_ACTION_TYPE_SUPPORT(control_msgs, GripperCommand);
}

void UROS2GripperCommandAction::Init()
{
    Super::Init();
    control_msgs__action__GripperCommand_SendGoal_Request__init(&GripperCommand_goal_request);
    control_msgs__action__GripperCommand_SendGoal_Response__init(&GripperCommand_goal_response);
    control_msgs__action__GripperCommand_GetResult_Request__init(&GripperCommand_result_request);
    control_msgs__action__GripperCommand_GetResult_Response__init(&GripperCommand_result_response);
    control_msgs__action__GripperCommand_FeedbackMessage__init(&GripperCommand_feedback_message);
}

void UROS2GripperCommandAction::Fini()
{
    control_msgs__action__GripperCommand_SendGoal_Request__fini(&GripperCommand_goal_request);
    control_msgs__action__GripperCommand_SendGoal_Response__fini(&GripperCommand_goal_response);
    control_msgs__action__GripperCommand_GetResult_Request__fini(&GripperCommand_result_request);
    control_msgs__action__GripperCommand_GetResult_Response__fini(&GripperCommand_result_response);
    control_msgs__action__GripperCommand_FeedbackMessage__fini(&GripperCommand_feedback_message);
    Super::Fini();
}

void UROS2GripperCommandAction::SetGoalRequest(const FROSGripperCommandSGReq& Goal)
{
    Goal.SetROS2(GripperCommand_goal_request);
}

void UROS2GripperCommandAction::GetGoalRequest(FROSGripperCommandSGReq& Goal) const
{
    Goal.SetFromROS2(GripperCommand_goal_request);
}

void UROS2GripperCommandAction::SetGoalResponse(const FROSGripperCommandSGRes& Goal)
{
    Goal.SetROS2(GripperCommand_goal_response);
}

void UROS2GripperCommandAction::GetGoalResponse(FROSGripperCommandSGRes& Goal) const
{
    Goal.SetFromROS2(GripperCommand_goal_response);
}

void UROS2GripperCommandAction::SetResultRequest(const FROSGripperCommandGRReq& Result)
{
    Result.SetROS2(GripperCommand_result_request);
}

void UROS2GripperCommandAction::GetResultRequest(FROSGripperCommandGRReq& Result) const
{
    Result.SetFromROS2(GripperCommand_result_request);
}

void UROS2GripperCommandAction::SetGoalIdToResultRequest(FROSGripperCommandGRReq& Result)
{
    for (int i = 0; i < 16; i++)
    {
        Result.GoalId[i] = GripperCommand_goal_request.goal_id.uuid[i];
    }
}

void UROS2GripperCommandAction::SetResultResponse(const FROSGripperCommandGRRes& Result)
{
    Result.SetROS2(GripperCommand_result_response);
}

void UROS2GripperCommandAction::GetResultResponse(FROSGripperCommandGRRes& Result) const
{
    Result.SetFromROS2(GripperCommand_result_response);
}


void UROS2GripperCommandAction::SetFeedback(const FROSGripperCommandFB& Feedback)
{
    Feedback.SetROS2(GripperCommand_feedback_message);
}

void UROS2GripperCommandAction::GetFeedback(FROSGripperCommandFB& Feedback) const
{
    Feedback.SetFromROS2(GripperCommand_feedback_message);
}

void UROS2GripperCommandAction::SetGoalIdToFeedback(FROSGripperCommandFB& Feedback)
{
    for (int i = 0; i < 16; i++)
    {
        Feedback.GoalId[i] = GripperCommand_goal_request.goal_id.uuid[i];
    }
}

void* UROS2GripperCommandAction::GetGoalRequest()
{
    return &GripperCommand_goal_request;
}

void* UROS2GripperCommandAction::GetGoalResponse()
{
    return &GripperCommand_goal_response;
}

void* UROS2GripperCommandAction::GetResultRequest()
{
    return &GripperCommand_result_request;
}

void* UROS2GripperCommandAction::GetResultResponse()
{
    return &GripperCommand_result_response;
}

void* UROS2GripperCommandAction::GetFeedbackMessage()
{
    return &GripperCommand_feedback_message;
}