// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/action/JointTrajectory.action - do not modify

#include "Actions/ROS2JointTrajAc.h"





const rosidl_action_type_support_t* UROS2JointTrajAction::GetTypeSupport() const
{
    return ROSIDL_GET_ACTION_TYPE_SUPPORT(control_msgs, JointTrajectory);
}

void UROS2JointTrajAction::Init()
{
    Super::Init();
    control_msgs__action__JointTrajectory_SendGoal_Request__init(&JointTrajectory_goal_request);
    control_msgs__action__JointTrajectory_SendGoal_Response__init(&JointTrajectory_goal_response);
    control_msgs__action__JointTrajectory_GetResult_Request__init(&JointTrajectory_result_request);
    control_msgs__action__JointTrajectory_GetResult_Response__init(&JointTrajectory_result_response);
    control_msgs__action__JointTrajectory_FeedbackMessage__init(&JointTrajectory_feedback_message);
}

void UROS2JointTrajAction::Fini()
{
    control_msgs__action__JointTrajectory_SendGoal_Request__fini(&JointTrajectory_goal_request);
    control_msgs__action__JointTrajectory_SendGoal_Response__fini(&JointTrajectory_goal_response);
    control_msgs__action__JointTrajectory_GetResult_Request__fini(&JointTrajectory_result_request);
    control_msgs__action__JointTrajectory_GetResult_Response__fini(&JointTrajectory_result_response);
    control_msgs__action__JointTrajectory_FeedbackMessage__fini(&JointTrajectory_feedback_message);
    Super::Fini();
}

void UROS2JointTrajAction::SetGoalRequest(const FROSJointTrajSGReq& Goal)
{
    Goal.SetROS2(JointTrajectory_goal_request);
}

void UROS2JointTrajAction::GetGoalRequest(FROSJointTrajSGReq& Goal) const
{
    Goal.SetFromROS2(JointTrajectory_goal_request);
}

void UROS2JointTrajAction::SetGoalResponse(const FROSJointTrajSGRes& Goal)
{
    Goal.SetROS2(JointTrajectory_goal_response);
}

void UROS2JointTrajAction::GetGoalResponse(FROSJointTrajSGRes& Goal) const
{
    Goal.SetFromROS2(JointTrajectory_goal_response);
}

void UROS2JointTrajAction::SetResultRequest(const FROSJointTrajGRReq& Result)
{
    Result.SetROS2(JointTrajectory_result_request);
}

void UROS2JointTrajAction::GetResultRequest(FROSJointTrajGRReq& Result) const
{
    Result.SetFromROS2(JointTrajectory_result_request);
}

void UROS2JointTrajAction::SetGoalIdToResultRequest(FROSJointTrajGRReq& Result)
{
    for (int i = 0; i < 16; i++)
    {
        Result.GoalId[i] = JointTrajectory_goal_request.goal_id.uuid[i];
    }
}

void UROS2JointTrajAction::SetResultResponse(const FROSJointTrajGRRes& Result)
{
    Result.SetROS2(JointTrajectory_result_response);
}

void UROS2JointTrajAction::GetResultResponse(FROSJointTrajGRRes& Result) const
{
    Result.SetFromROS2(JointTrajectory_result_response);
}


void UROS2JointTrajAction::SetFeedback(const FROSJointTrajFB& Feedback)
{
    Feedback.SetROS2(JointTrajectory_feedback_message);
}

void UROS2JointTrajAction::GetFeedback(FROSJointTrajFB& Feedback) const
{
    Feedback.SetFromROS2(JointTrajectory_feedback_message);
}

void UROS2JointTrajAction::SetGoalIdToFeedback(FROSJointTrajFB& Feedback)
{
    for (int i = 0; i < 16; i++)
    {
        Feedback.GoalId[i] = JointTrajectory_goal_request.goal_id.uuid[i];
    }
}

void* UROS2JointTrajAction::GetGoalRequest()
{
    return &JointTrajectory_goal_request;
}

void* UROS2JointTrajAction::GetGoalResponse()
{
    return &JointTrajectory_goal_response;
}

void* UROS2JointTrajAction::GetResultRequest()
{
    return &JointTrajectory_result_request;
}

void* UROS2JointTrajAction::GetResultResponse()
{
    return &JointTrajectory_result_response;
}

void* UROS2JointTrajAction::GetFeedbackMessage()
{
    return &JointTrajectory_feedback_message;
}