// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/action/PointHead.action - do not modify

#include "Actions/ROS2PointHead.h"





const rosidl_action_type_support_t* UROS2PointHeadAction::GetTypeSupport() const
{
    return ROSIDL_GET_ACTION_TYPE_SUPPORT(control_msgs, PointHead);
}

void UROS2PointHeadAction::Init()
{
    Super::Init();
    control_msgs__action__PointHead_SendGoal_Request__init(&PointHead_goal_request);
    control_msgs__action__PointHead_SendGoal_Response__init(&PointHead_goal_response);
    control_msgs__action__PointHead_GetResult_Request__init(&PointHead_result_request);
    control_msgs__action__PointHead_GetResult_Response__init(&PointHead_result_response);
    control_msgs__action__PointHead_FeedbackMessage__init(&PointHead_feedback_message);
}

void UROS2PointHeadAction::Fini()
{
    control_msgs__action__PointHead_SendGoal_Request__fini(&PointHead_goal_request);
    control_msgs__action__PointHead_SendGoal_Response__fini(&PointHead_goal_response);
    control_msgs__action__PointHead_GetResult_Request__fini(&PointHead_result_request);
    control_msgs__action__PointHead_GetResult_Response__fini(&PointHead_result_response);
    control_msgs__action__PointHead_FeedbackMessage__fini(&PointHead_feedback_message);
    Super::Fini();
}

void UROS2PointHeadAction::SetGoalRequest(const FROSPointHeadSGReq& Goal)
{
    Goal.SetROS2(PointHead_goal_request);
}

void UROS2PointHeadAction::GetGoalRequest(FROSPointHeadSGReq& Goal) const
{
    Goal.SetFromROS2(PointHead_goal_request);
}

void UROS2PointHeadAction::SetGoalResponse(const FROSPointHeadSGRes& Goal)
{
    Goal.SetROS2(PointHead_goal_response);
}

void UROS2PointHeadAction::GetGoalResponse(FROSPointHeadSGRes& Goal) const
{
    Goal.SetFromROS2(PointHead_goal_response);
}

void UROS2PointHeadAction::SetResultRequest(const FROSPointHeadGRReq& Result)
{
    Result.SetROS2(PointHead_result_request);
}

void UROS2PointHeadAction::GetResultRequest(FROSPointHeadGRReq& Result) const
{
    Result.SetFromROS2(PointHead_result_request);
}

void UROS2PointHeadAction::SetGoalIdToResultRequest(FROSPointHeadGRReq& Result)
{
    for (int i = 0; i < 16; i++)
    {
        Result.GoalId[i] = PointHead_goal_request.goal_id.uuid[i];
    }
}

void UROS2PointHeadAction::SetResultResponse(const FROSPointHeadGRRes& Result)
{
    Result.SetROS2(PointHead_result_response);
}

void UROS2PointHeadAction::GetResultResponse(FROSPointHeadGRRes& Result) const
{
    Result.SetFromROS2(PointHead_result_response);
}


void UROS2PointHeadAction::SetFeedback(const FROSPointHeadFB& Feedback)
{
    Feedback.SetROS2(PointHead_feedback_message);
}

void UROS2PointHeadAction::GetFeedback(FROSPointHeadFB& Feedback) const
{
    Feedback.SetFromROS2(PointHead_feedback_message);
}

void UROS2PointHeadAction::SetGoalIdToFeedback(FROSPointHeadFB& Feedback)
{
    for (int i = 0; i < 16; i++)
    {
        Feedback.GoalId[i] = PointHead_goal_request.goal_id.uuid[i];
    }
}

void* UROS2PointHeadAction::GetGoalRequest()
{
    return &PointHead_goal_request;
}

void* UROS2PointHeadAction::GetGoalResponse()
{
    return &PointHead_goal_response;
}

void* UROS2PointHeadAction::GetResultRequest()
{
    return &PointHead_result_request;
}

void* UROS2PointHeadAction::GetResultResponse()
{
    return &PointHead_result_response;
}

void* UROS2PointHeadAction::GetFeedbackMessage()
{
    return &PointHead_feedback_message;
}