// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/action/ParallelGripperCommand.action - do not modify

#include "Actions/ROS2ParallelGripperCommand.h"





const rosidl_action_type_support_t* UROS2ParallelGripperCommandAction::GetTypeSupport() const
{
    return ROSIDL_GET_ACTION_TYPE_SUPPORT(control_msgs, ParallelGripperCommand);
}

void UROS2ParallelGripperCommandAction::Init()
{
    Super::Init();
    control_msgs__action__ParallelGripperCommand_SendGoal_Request__init(&ParallelGripperCommand_goal_request);
    control_msgs__action__ParallelGripperCommand_SendGoal_Response__init(&ParallelGripperCommand_goal_response);
    control_msgs__action__ParallelGripperCommand_GetResult_Request__init(&ParallelGripperCommand_result_request);
    control_msgs__action__ParallelGripperCommand_GetResult_Response__init(&ParallelGripperCommand_result_response);
    control_msgs__action__ParallelGripperCommand_FeedbackMessage__init(&ParallelGripperCommand_feedback_message);
}

void UROS2ParallelGripperCommandAction::Fini()
{
    control_msgs__action__ParallelGripperCommand_SendGoal_Request__fini(&ParallelGripperCommand_goal_request);
    control_msgs__action__ParallelGripperCommand_SendGoal_Response__fini(&ParallelGripperCommand_goal_response);
    control_msgs__action__ParallelGripperCommand_GetResult_Request__fini(&ParallelGripperCommand_result_request);
    control_msgs__action__ParallelGripperCommand_GetResult_Response__fini(&ParallelGripperCommand_result_response);
    control_msgs__action__ParallelGripperCommand_FeedbackMessage__fini(&ParallelGripperCommand_feedback_message);
    Super::Fini();
}

void UROS2ParallelGripperCommandAction::SetGoalRequest(const FROSParallelGripperCommandSGReq& Goal)
{
    Goal.SetROS2(ParallelGripperCommand_goal_request);
}

void UROS2ParallelGripperCommandAction::GetGoalRequest(FROSParallelGripperCommandSGReq& Goal) const
{
    Goal.SetFromROS2(ParallelGripperCommand_goal_request);
}

void UROS2ParallelGripperCommandAction::SetGoalResponse(const FROSParallelGripperCommandSGRes& Goal)
{
    Goal.SetROS2(ParallelGripperCommand_goal_response);
}

void UROS2ParallelGripperCommandAction::GetGoalResponse(FROSParallelGripperCommandSGRes& Goal) const
{
    Goal.SetFromROS2(ParallelGripperCommand_goal_response);
}

void UROS2ParallelGripperCommandAction::SetResultRequest(const FROSParallelGripperCommandGRReq& Result)
{
    Result.SetROS2(ParallelGripperCommand_result_request);
}

void UROS2ParallelGripperCommandAction::GetResultRequest(FROSParallelGripperCommandGRReq& Result) const
{
    Result.SetFromROS2(ParallelGripperCommand_result_request);
}

void UROS2ParallelGripperCommandAction::SetGoalIdToResultRequest(FROSParallelGripperCommandGRReq& Result)
{
    for (int i = 0; i < 16; i++)
    {
        Result.GoalId[i] = ParallelGripperCommand_goal_request.goal_id.uuid[i];
    }
}

void UROS2ParallelGripperCommandAction::SetResultResponse(const FROSParallelGripperCommandGRRes& Result)
{
    Result.SetROS2(ParallelGripperCommand_result_response);
}

void UROS2ParallelGripperCommandAction::GetResultResponse(FROSParallelGripperCommandGRRes& Result) const
{
    Result.SetFromROS2(ParallelGripperCommand_result_response);
}


void UROS2ParallelGripperCommandAction::SetFeedback(const FROSParallelGripperCommandFB& Feedback)
{
    Feedback.SetROS2(ParallelGripperCommand_feedback_message);
}

void UROS2ParallelGripperCommandAction::GetFeedback(FROSParallelGripperCommandFB& Feedback) const
{
    Feedback.SetFromROS2(ParallelGripperCommand_feedback_message);
}

void UROS2ParallelGripperCommandAction::SetGoalIdToFeedback(FROSParallelGripperCommandFB& Feedback)
{
    for (int i = 0; i < 16; i++)
    {
        Feedback.GoalId[i] = ParallelGripperCommand_goal_request.goal_id.uuid[i];
    }
}

void* UROS2ParallelGripperCommandAction::GetGoalRequest()
{
    return &ParallelGripperCommand_goal_request;
}

void* UROS2ParallelGripperCommandAction::GetGoalResponse()
{
    return &ParallelGripperCommand_goal_response;
}

void* UROS2ParallelGripperCommandAction::GetResultRequest()
{
    return &ParallelGripperCommand_result_request;
}

void* UROS2ParallelGripperCommandAction::GetResultResponse()
{
    return &ParallelGripperCommand_result_response;
}

void* UROS2ParallelGripperCommandAction::GetFeedbackMessage()
{
    return &ParallelGripperCommand_feedback_message;
}