// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/action/SingleJointPosition.action - do not modify

#include "Actions/ROS2SingleJointPosition.h"





const rosidl_action_type_support_t* UROS2SingleJointPositionAction::GetTypeSupport() const
{
    return ROSIDL_GET_ACTION_TYPE_SUPPORT(control_msgs, SingleJointPosition);
}

void UROS2SingleJointPositionAction::Init()
{
    Super::Init();
    control_msgs__action__SingleJointPosition_SendGoal_Request__init(&SingleJointPosition_goal_request);
    control_msgs__action__SingleJointPosition_SendGoal_Response__init(&SingleJointPosition_goal_response);
    control_msgs__action__SingleJointPosition_GetResult_Request__init(&SingleJointPosition_result_request);
    control_msgs__action__SingleJointPosition_GetResult_Response__init(&SingleJointPosition_result_response);
    control_msgs__action__SingleJointPosition_FeedbackMessage__init(&SingleJointPosition_feedback_message);
}

void UROS2SingleJointPositionAction::Fini()
{
    control_msgs__action__SingleJointPosition_SendGoal_Request__fini(&SingleJointPosition_goal_request);
    control_msgs__action__SingleJointPosition_SendGoal_Response__fini(&SingleJointPosition_goal_response);
    control_msgs__action__SingleJointPosition_GetResult_Request__fini(&SingleJointPosition_result_request);
    control_msgs__action__SingleJointPosition_GetResult_Response__fini(&SingleJointPosition_result_response);
    control_msgs__action__SingleJointPosition_FeedbackMessage__fini(&SingleJointPosition_feedback_message);
    Super::Fini();
}

void UROS2SingleJointPositionAction::SetGoalRequest(const FROSSingleJointPositionSGReq& Goal)
{
    Goal.SetROS2(SingleJointPosition_goal_request);
}

void UROS2SingleJointPositionAction::GetGoalRequest(FROSSingleJointPositionSGReq& Goal) const
{
    Goal.SetFromROS2(SingleJointPosition_goal_request);
}

void UROS2SingleJointPositionAction::SetGoalResponse(const FROSSingleJointPositionSGRes& Goal)
{
    Goal.SetROS2(SingleJointPosition_goal_response);
}

void UROS2SingleJointPositionAction::GetGoalResponse(FROSSingleJointPositionSGRes& Goal) const
{
    Goal.SetFromROS2(SingleJointPosition_goal_response);
}

void UROS2SingleJointPositionAction::SetResultRequest(const FROSSingleJointPositionGRReq& Result)
{
    Result.SetROS2(SingleJointPosition_result_request);
}

void UROS2SingleJointPositionAction::GetResultRequest(FROSSingleJointPositionGRReq& Result) const
{
    Result.SetFromROS2(SingleJointPosition_result_request);
}

void UROS2SingleJointPositionAction::SetGoalIdToResultRequest(FROSSingleJointPositionGRReq& Result)
{
    for (int i = 0; i < 16; i++)
    {
        Result.GoalId[i] = SingleJointPosition_goal_request.goal_id.uuid[i];
    }
}

void UROS2SingleJointPositionAction::SetResultResponse(const FROSSingleJointPositionGRRes& Result)
{
    Result.SetROS2(SingleJointPosition_result_response);
}

void UROS2SingleJointPositionAction::GetResultResponse(FROSSingleJointPositionGRRes& Result) const
{
    Result.SetFromROS2(SingleJointPosition_result_response);
}


void UROS2SingleJointPositionAction::SetFeedback(const FROSSingleJointPositionFB& Feedback)
{
    Feedback.SetROS2(SingleJointPosition_feedback_message);
}

void UROS2SingleJointPositionAction::GetFeedback(FROSSingleJointPositionFB& Feedback) const
{
    Feedback.SetFromROS2(SingleJointPosition_feedback_message);
}

void UROS2SingleJointPositionAction::SetGoalIdToFeedback(FROSSingleJointPositionFB& Feedback)
{
    for (int i = 0; i < 16; i++)
    {
        Feedback.GoalId[i] = SingleJointPosition_goal_request.goal_id.uuid[i];
    }
}

void* UROS2SingleJointPositionAction::GetGoalRequest()
{
    return &SingleJointPosition_goal_request;
}

void* UROS2SingleJointPositionAction::GetGoalResponse()
{
    return &SingleJointPosition_goal_response;
}

void* UROS2SingleJointPositionAction::GetResultRequest()
{
    return &SingleJointPosition_result_request;
}

void* UROS2SingleJointPositionAction::GetResultResponse()
{
    return &SingleJointPosition_result_response;
}

void* UROS2SingleJointPositionAction::GetFeedbackMessage()
{
    return &SingleJointPosition_feedback_message;
}