// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/action/FollowJointTrajectory.action - do not modify

#include "Actions/ROS2FollowJointTraj.h"





const rosidl_action_type_support_t* UROS2FollowJointTrajAction::GetTypeSupport() const
{
    return ROSIDL_GET_ACTION_TYPE_SUPPORT(control_msgs, FollowJointTrajectory);
}

void UROS2FollowJointTrajAction::Init()
{
    Super::Init();
    control_msgs__action__FollowJointTrajectory_SendGoal_Request__init(&FollowJointTrajectory_goal_request);
    control_msgs__action__FollowJointTrajectory_SendGoal_Response__init(&FollowJointTrajectory_goal_response);
    control_msgs__action__FollowJointTrajectory_GetResult_Request__init(&FollowJointTrajectory_result_request);
    control_msgs__action__FollowJointTrajectory_GetResult_Response__init(&FollowJointTrajectory_result_response);
    control_msgs__action__FollowJointTrajectory_FeedbackMessage__init(&FollowJointTrajectory_feedback_message);
}

void UROS2FollowJointTrajAction::Fini()
{
    control_msgs__action__FollowJointTrajectory_SendGoal_Request__fini(&FollowJointTrajectory_goal_request);
    control_msgs__action__FollowJointTrajectory_SendGoal_Response__fini(&FollowJointTrajectory_goal_response);
    control_msgs__action__FollowJointTrajectory_GetResult_Request__fini(&FollowJointTrajectory_result_request);
    control_msgs__action__FollowJointTrajectory_GetResult_Response__fini(&FollowJointTrajectory_result_response);
    control_msgs__action__FollowJointTrajectory_FeedbackMessage__fini(&FollowJointTrajectory_feedback_message);
    Super::Fini();
}

void UROS2FollowJointTrajAction::SetGoalRequest(const FROSFollowJointTrajSGReq& Goal)
{
    Goal.SetROS2(FollowJointTrajectory_goal_request);
}

void UROS2FollowJointTrajAction::GetGoalRequest(FROSFollowJointTrajSGReq& Goal) const
{
    Goal.SetFromROS2(FollowJointTrajectory_goal_request);
}

void UROS2FollowJointTrajAction::SetGoalResponse(const FROSFollowJointTrajSGRes& Goal)
{
    Goal.SetROS2(FollowJointTrajectory_goal_response);
}

void UROS2FollowJointTrajAction::GetGoalResponse(FROSFollowJointTrajSGRes& Goal) const
{
    Goal.SetFromROS2(FollowJointTrajectory_goal_response);
}

void UROS2FollowJointTrajAction::SetResultRequest(const FROSFollowJointTrajGRReq& Result)
{
    Result.SetROS2(FollowJointTrajectory_result_request);
}

void UROS2FollowJointTrajAction::GetResultRequest(FROSFollowJointTrajGRReq& Result) const
{
    Result.SetFromROS2(FollowJointTrajectory_result_request);
}

void UROS2FollowJointTrajAction::SetGoalIdToResultRequest(FROSFollowJointTrajGRReq& Result)
{
    for (int i = 0; i < 16; i++)
    {
        Result.GoalId[i] = FollowJointTrajectory_goal_request.goal_id.uuid[i];
    }
}

void UROS2FollowJointTrajAction::SetResultResponse(const FROSFollowJointTrajGRRes& Result)
{
    Result.SetROS2(FollowJointTrajectory_result_response);
}

void UROS2FollowJointTrajAction::GetResultResponse(FROSFollowJointTrajGRRes& Result) const
{
    Result.SetFromROS2(FollowJointTrajectory_result_response);
}


void UROS2FollowJointTrajAction::SetFeedback(const FROSFollowJointTrajFB& Feedback)
{
    Feedback.SetROS2(FollowJointTrajectory_feedback_message);
}

void UROS2FollowJointTrajAction::GetFeedback(FROSFollowJointTrajFB& Feedback) const
{
    Feedback.SetFromROS2(FollowJointTrajectory_feedback_message);
}

void UROS2FollowJointTrajAction::SetGoalIdToFeedback(FROSFollowJointTrajFB& Feedback)
{
    for (int i = 0; i < 16; i++)
    {
        Feedback.GoalId[i] = FollowJointTrajectory_goal_request.goal_id.uuid[i];
    }
}

void* UROS2FollowJointTrajAction::GetGoalRequest()
{
    return &FollowJointTrajectory_goal_request;
}

void* UROS2FollowJointTrajAction::GetGoalResponse()
{
    return &FollowJointTrajectory_goal_response;
}

void* UROS2FollowJointTrajAction::GetResultRequest()
{
    return &FollowJointTrajectory_result_request;
}

void* UROS2FollowJointTrajAction::GetResultResponse()
{
    return &FollowJointTrajectory_result_response;
}

void* UROS2FollowJointTrajAction::GetFeedbackMessage()
{
    return &FollowJointTrajectory_feedback_message;
}