// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from clf_ue_audio_msgs/action/AudioStreaming.action - do not modify

#include "Actions/ROS2AudioStreaming.h"





const rosidl_action_type_support_t* UROS2AudioStreamingAction::GetTypeSupport() const
{
    return ROSIDL_GET_ACTION_TYPE_SUPPORT(clf_ue_audio_msgs, AudioStreaming);
}

void UROS2AudioStreamingAction::Init()
{
    Super::Init();
    clf_ue_audio_msgs__action__AudioStreaming_SendGoal_Request__init(&AudioStreaming_goal_request);
    clf_ue_audio_msgs__action__AudioStreaming_SendGoal_Response__init(&AudioStreaming_goal_response);
    clf_ue_audio_msgs__action__AudioStreaming_GetResult_Request__init(&AudioStreaming_result_request);
    clf_ue_audio_msgs__action__AudioStreaming_GetResult_Response__init(&AudioStreaming_result_response);
    clf_ue_audio_msgs__action__AudioStreaming_FeedbackMessage__init(&AudioStreaming_feedback_message);
}

void UROS2AudioStreamingAction::Fini()
{
    clf_ue_audio_msgs__action__AudioStreaming_SendGoal_Request__fini(&AudioStreaming_goal_request);
    clf_ue_audio_msgs__action__AudioStreaming_SendGoal_Response__fini(&AudioStreaming_goal_response);
    clf_ue_audio_msgs__action__AudioStreaming_GetResult_Request__fini(&AudioStreaming_result_request);
    clf_ue_audio_msgs__action__AudioStreaming_GetResult_Response__fini(&AudioStreaming_result_response);
    clf_ue_audio_msgs__action__AudioStreaming_FeedbackMessage__fini(&AudioStreaming_feedback_message);
    Super::Fini();
}

void UROS2AudioStreamingAction::SetGoalRequest(const FROSAudioStreamingSGReq& Goal)
{
    Goal.SetROS2(AudioStreaming_goal_request);
}

void UROS2AudioStreamingAction::GetGoalRequest(FROSAudioStreamingSGReq& Goal) const
{
    Goal.SetFromROS2(AudioStreaming_goal_request);
}

void UROS2AudioStreamingAction::SetGoalResponse(const FROSAudioStreamingSGRes& Goal)
{
    Goal.SetROS2(AudioStreaming_goal_response);
}

void UROS2AudioStreamingAction::GetGoalResponse(FROSAudioStreamingSGRes& Goal) const
{
    Goal.SetFromROS2(AudioStreaming_goal_response);
}

void UROS2AudioStreamingAction::SetResultRequest(const FROSAudioStreamingGRReq& Result)
{
    Result.SetROS2(AudioStreaming_result_request);
}

void UROS2AudioStreamingAction::GetResultRequest(FROSAudioStreamingGRReq& Result) const
{
    Result.SetFromROS2(AudioStreaming_result_request);
}

void UROS2AudioStreamingAction::SetGoalIdToResultRequest(FROSAudioStreamingGRReq& Result)
{
    for (int i = 0; i < 16; i++)
    {
        Result.GoalId[i] = AudioStreaming_goal_request.goal_id.uuid[i];
    }
}

void UROS2AudioStreamingAction::SetResultResponse(const FROSAudioStreamingGRRes& Result)
{
    Result.SetROS2(AudioStreaming_result_response);
}

void UROS2AudioStreamingAction::GetResultResponse(FROSAudioStreamingGRRes& Result) const
{
    Result.SetFromROS2(AudioStreaming_result_response);
}


void UROS2AudioStreamingAction::SetFeedback(const FROSAudioStreamingFB& Feedback)
{
    Feedback.SetROS2(AudioStreaming_feedback_message);
}

void UROS2AudioStreamingAction::GetFeedback(FROSAudioStreamingFB& Feedback) const
{
    Feedback.SetFromROS2(AudioStreaming_feedback_message);
}

void UROS2AudioStreamingAction::SetGoalIdToFeedback(FROSAudioStreamingFB& Feedback)
{
    for (int i = 0; i < 16; i++)
    {
        Feedback.GoalId[i] = AudioStreaming_goal_request.goal_id.uuid[i];
    }
}

void* UROS2AudioStreamingAction::GetGoalRequest()
{
    return &AudioStreaming_goal_request;
}

void* UROS2AudioStreamingAction::GetGoalResponse()
{
    return &AudioStreaming_goal_response;
}

void* UROS2AudioStreamingAction::GetResultRequest()
{
    return &AudioStreaming_result_request;
}

void* UROS2AudioStreamingAction::GetResultResponse()
{
    return &AudioStreaming_result_response;
}

void* UROS2AudioStreamingAction::GetFeedbackMessage()
{
    return &AudioStreaming_feedback_message;
}