// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/action/ExecuteMotionPrimitiveSequence.action - do not modify

#include "Actions/ROS2ExecuteMotionPrimitiveSequence.h"





const rosidl_action_type_support_t* UROS2ExecuteMotionPrimitiveSequenceAction::GetTypeSupport() const
{
    return ROSIDL_GET_ACTION_TYPE_SUPPORT(control_msgs, ExecuteMotionPrimitiveSequence);
}

void UROS2ExecuteMotionPrimitiveSequenceAction::Init()
{
    Super::Init();
    control_msgs__action__ExecuteMotionPrimitiveSequence_SendGoal_Request__init(&ExecuteMotionPrimitiveSequence_goal_request);
    control_msgs__action__ExecuteMotionPrimitiveSequence_SendGoal_Response__init(&ExecuteMotionPrimitiveSequence_goal_response);
    control_msgs__action__ExecuteMotionPrimitiveSequence_GetResult_Request__init(&ExecuteMotionPrimitiveSequence_result_request);
    control_msgs__action__ExecuteMotionPrimitiveSequence_GetResult_Response__init(&ExecuteMotionPrimitiveSequence_result_response);
    control_msgs__action__ExecuteMotionPrimitiveSequence_FeedbackMessage__init(&ExecuteMotionPrimitiveSequence_feedback_message);
}

void UROS2ExecuteMotionPrimitiveSequenceAction::Fini()
{
    control_msgs__action__ExecuteMotionPrimitiveSequence_SendGoal_Request__fini(&ExecuteMotionPrimitiveSequence_goal_request);
    control_msgs__action__ExecuteMotionPrimitiveSequence_SendGoal_Response__fini(&ExecuteMotionPrimitiveSequence_goal_response);
    control_msgs__action__ExecuteMotionPrimitiveSequence_GetResult_Request__fini(&ExecuteMotionPrimitiveSequence_result_request);
    control_msgs__action__ExecuteMotionPrimitiveSequence_GetResult_Response__fini(&ExecuteMotionPrimitiveSequence_result_response);
    control_msgs__action__ExecuteMotionPrimitiveSequence_FeedbackMessage__fini(&ExecuteMotionPrimitiveSequence_feedback_message);
    Super::Fini();
}

void UROS2ExecuteMotionPrimitiveSequenceAction::SetGoalRequest(const FROSExecuteMotionPrimitiveSequenceSGReq& Goal)
{
    Goal.SetROS2(ExecuteMotionPrimitiveSequence_goal_request);
}

void UROS2ExecuteMotionPrimitiveSequenceAction::GetGoalRequest(FROSExecuteMotionPrimitiveSequenceSGReq& Goal) const
{
    Goal.SetFromROS2(ExecuteMotionPrimitiveSequence_goal_request);
}

void UROS2ExecuteMotionPrimitiveSequenceAction::SetGoalResponse(const FROSExecuteMotionPrimitiveSequenceSGRes& Goal)
{
    Goal.SetROS2(ExecuteMotionPrimitiveSequence_goal_response);
}

void UROS2ExecuteMotionPrimitiveSequenceAction::GetGoalResponse(FROSExecuteMotionPrimitiveSequenceSGRes& Goal) const
{
    Goal.SetFromROS2(ExecuteMotionPrimitiveSequence_goal_response);
}

void UROS2ExecuteMotionPrimitiveSequenceAction::SetResultRequest(const FROSExecuteMotionPrimitiveSequenceGRReq& Result)
{
    Result.SetROS2(ExecuteMotionPrimitiveSequence_result_request);
}

void UROS2ExecuteMotionPrimitiveSequenceAction::GetResultRequest(FROSExecuteMotionPrimitiveSequenceGRReq& Result) const
{
    Result.SetFromROS2(ExecuteMotionPrimitiveSequence_result_request);
}

void UROS2ExecuteMotionPrimitiveSequenceAction::SetGoalIdToResultRequest(FROSExecuteMotionPrimitiveSequenceGRReq& Result)
{
    for (int i = 0; i < 16; i++)
    {
        Result.GoalId[i] = ExecuteMotionPrimitiveSequence_goal_request.goal_id.uuid[i];
    }
}

void UROS2ExecuteMotionPrimitiveSequenceAction::SetResultResponse(const FROSExecuteMotionPrimitiveSequenceGRRes& Result)
{
    Result.SetROS2(ExecuteMotionPrimitiveSequence_result_response);
}

void UROS2ExecuteMotionPrimitiveSequenceAction::GetResultResponse(FROSExecuteMotionPrimitiveSequenceGRRes& Result) const
{
    Result.SetFromROS2(ExecuteMotionPrimitiveSequence_result_response);
}


void UROS2ExecuteMotionPrimitiveSequenceAction::SetFeedback(const FROSExecuteMotionPrimitiveSequenceFB& Feedback)
{
    Feedback.SetROS2(ExecuteMotionPrimitiveSequence_feedback_message);
}

void UROS2ExecuteMotionPrimitiveSequenceAction::GetFeedback(FROSExecuteMotionPrimitiveSequenceFB& Feedback) const
{
    Feedback.SetFromROS2(ExecuteMotionPrimitiveSequence_feedback_message);
}

void UROS2ExecuteMotionPrimitiveSequenceAction::SetGoalIdToFeedback(FROSExecuteMotionPrimitiveSequenceFB& Feedback)
{
    for (int i = 0; i < 16; i++)
    {
        Feedback.GoalId[i] = ExecuteMotionPrimitiveSequence_goal_request.goal_id.uuid[i];
    }
}

void* UROS2ExecuteMotionPrimitiveSequenceAction::GetGoalRequest()
{
    return &ExecuteMotionPrimitiveSequence_goal_request;
}

void* UROS2ExecuteMotionPrimitiveSequenceAction::GetGoalResponse()
{
    return &ExecuteMotionPrimitiveSequence_goal_response;
}

void* UROS2ExecuteMotionPrimitiveSequenceAction::GetResultRequest()
{
    return &ExecuteMotionPrimitiveSequence_result_request;
}

void* UROS2ExecuteMotionPrimitiveSequenceAction::GetResultResponse()
{
    return &ExecuteMotionPrimitiveSequence_result_response;
}

void* UROS2ExecuteMotionPrimitiveSequenceAction::GetFeedbackMessage()
{
    return &ExecuteMotionPrimitiveSequence_feedback_message;
}