// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/srv/QueryTrajectoryState.srv - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/srv/query_trajectory_state.h"

// rclUE
#include "Srvs/ROS2GenericSrv.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Time.h"

#include "rosidl_runtime_c/string_functions.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"


// Generated
#include "ROS2QueryTrajState.generated.h"

// potential problem: if this struct is defined multiple times!
USTRUCT(Blueprintable)
struct RCLUE_API FROSQueryTrajStateReq
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSTime Time;

	

	FROSQueryTrajStateReq()
	{
		
	}

	void SetFromROS2(const control_msgs__srv__QueryTrajectoryState_Request& in_ros_data)
	{
    	Time.SetFromROS2(in_ros_data.time);

		
	}

	void SetROS2(control_msgs__srv__QueryTrajectoryState_Request& out_ros_data) const
	{
    	Time.SetROS2(out_ros_data.time);

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSQueryTrajStateRes
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bSuccess = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString Message;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FString> Name;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<double> Position;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<double> Velocity;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<double> Acceleration;

	

	FROSQueryTrajStateRes()
	{
		
	}

	void SetFromROS2(const control_msgs__srv__QueryTrajectoryState_Response& in_ros_data)
	{
    	bSuccess = in_ros_data.success;

		Message = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.message);

		UROS2Utils::StringSequenceROSToUEArray<rosidl_runtime_c__String>(in_ros_data.name.data, Name, in_ros_data.name.size);

		UROS2Utils::SequenceROSToUEArray<double, double>(in_ros_data.position.data, Position, in_ros_data.position.size);

		UROS2Utils::SequenceROSToUEArray<double, double>(in_ros_data.velocity.data, Velocity, in_ros_data.velocity.size);

		UROS2Utils::SequenceROSToUEArray<double, double>(in_ros_data.acceleration.data, Acceleration, in_ros_data.acceleration.size);

		
	}

	void SetROS2(control_msgs__srv__QueryTrajectoryState_Response& out_ros_data) const
	{
    	out_ros_data.success = bSuccess;

		UROS2Utils::StringUEToROS(Message, out_ros_data.message);

		if (out_ros_data.name.data) {
		rosidl_runtime_c__String__Sequence__fini(&out_ros_data.name);
		}
		if (!rosidl_runtime_c__String__Sequence__init(&out_ros_data.name, Name.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.name  "));}
		UROS2Utils::StringArrayUEToROSSequence(Name, out_ros_data.name.data, Name.Num());

		if (out_ros_data.position.data) {
		rosidl_runtime_c__float64__Sequence__fini(&out_ros_data.position);
		}
		if (!rosidl_runtime_c__float64__Sequence__init(&out_ros_data.position, Position.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.position  "));}
		UROS2Utils::ArrayUEToROSSequence<double, double>(Position, out_ros_data.position.data, Position.Num());

		if (out_ros_data.velocity.data) {
		rosidl_runtime_c__float64__Sequence__fini(&out_ros_data.velocity);
		}
		if (!rosidl_runtime_c__float64__Sequence__init(&out_ros_data.velocity, Velocity.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.velocity  "));}
		UROS2Utils::ArrayUEToROSSequence<double, double>(Velocity, out_ros_data.velocity.data, Velocity.Num());

		if (out_ros_data.acceleration.data) {
		rosidl_runtime_c__float64__Sequence__fini(&out_ros_data.acceleration);
		}
		if (!rosidl_runtime_c__float64__Sequence__init(&out_ros_data.acceleration, Acceleration.Num())) {UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.acceleration  "));}
		UROS2Utils::ArrayUEToROSSequence<double, double>(Acceleration, out_ros_data.acceleration.data, Acceleration.Num());

		
	}
};

UCLASS()
class RCLUE_API UROS2QueryTrajStateSrv : public UROS2GenericSrv
{
	GENERATED_BODY()

public:
  	UFUNCTION(BlueprintCallable)
	virtual void Init() override;

  	UFUNCTION(BlueprintCallable)
	virtual void Fini() override;

	virtual const rosidl_service_type_support_t* GetTypeSupport() const override;
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void SetRequest(const FROSQueryTrajStateReq& Request);
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void GetRequest(FROSQueryTrajStateReq& Request) const;
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void SetResponse(const FROSQueryTrajStateRes& Response);
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void GetResponse(FROSQueryTrajStateRes& Response) const;
	
	virtual void* GetRequest() override;
	virtual void* GetResponse() override;

	
	

private:
	virtual FString SrvRequestToString() const override;
	virtual FString SrvResponseToString() const override;

	control_msgs__srv__QueryTrajectoryState_Request QueryTrajectoryState_req;
	control_msgs__srv__QueryTrajectoryState_Response QueryTrajectoryState_res;
};