// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/srv/QueryCalibrationState.srv - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "control_msgs/srv/query_calibration_state.h"

// rclUE
#include "Srvs/ROS2GenericSrv.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)



// Generated
#include "ROS2QueryCalibrationState.generated.h"

// potential problem: if this struct is defined multiple times!
USTRUCT(Blueprintable)
struct RCLUE_API FROSQueryCalibrationStateReq
{
	GENERATED_BODY()

public:
	

	

	FROSQueryCalibrationStateReq()
	{
		
	}

	void SetFromROS2(const control_msgs__srv__QueryCalibrationState_Request& in_ros_data)
	{
    	
	}

	void SetROS2(control_msgs__srv__QueryCalibrationState_Request& out_ros_data) const
	{
    	
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSQueryCalibrationStateRes
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bIsCalibrated = false;

	

	FROSQueryCalibrationStateRes()
	{
		
	}

	void SetFromROS2(const control_msgs__srv__QueryCalibrationState_Response& in_ros_data)
	{
    	bIsCalibrated = in_ros_data.is_calibrated;

		
	}

	void SetROS2(control_msgs__srv__QueryCalibrationState_Response& out_ros_data) const
	{
    	out_ros_data.is_calibrated = bIsCalibrated;

		
	}
};

UCLASS()
class RCLUE_API UROS2QueryCalibrationStateSrv : public UROS2GenericSrv
{
	GENERATED_BODY()

public:
  	UFUNCTION(BlueprintCallable)
	virtual void Init() override;

  	UFUNCTION(BlueprintCallable)
	virtual void Fini() override;

	virtual const rosidl_service_type_support_t* GetTypeSupport() const override;
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void SetRequest(const FROSQueryCalibrationStateReq& Request);
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void GetRequest(FROSQueryCalibrationStateReq& Request) const;
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void SetResponse(const FROSQueryCalibrationStateRes& Response);
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void GetResponse(FROSQueryCalibrationStateRes& Response) const;
	
	virtual void* GetRequest() override;
	virtual void* GetResponse() override;

	
	

private:
	virtual FString SrvRequestToString() const override;
	virtual FString SrvResponseToString() const override;

	control_msgs__srv__QueryCalibrationState_Request QueryCalibrationState_req;
	control_msgs__srv__QueryCalibrationState_Response QueryCalibrationState_res;
};