// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/MotionPrimitiveSequence.msg - do not modify

#include "Msgs/ROS2MotionPrimitiveSequence.h"

#include "Kismet/GameplayStatics.h"



void UROS2MotionPrimitiveSequenceMsg::Init()
{
	control_msgs__msg__MotionPrimitiveSequence__init(&motion_primitive_sequence_msg);
}

void UROS2MotionPrimitiveSequenceMsg::Fini()
{
	control_msgs__msg__MotionPrimitiveSequence__fini(&motion_primitive_sequence_msg);
}

const rosidl_message_type_support_t* UROS2MotionPrimitiveSequenceMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, MotionPrimitiveSequence);
}

void UROS2MotionPrimitiveSequenceMsg::SetMsg(const FROSMotionPrimitiveSequence& Inputs)
{
    Inputs.SetROS2(motion_primitive_sequence_msg);
}

void UROS2MotionPrimitiveSequenceMsg::GetMsg(FROSMotionPrimitiveSequence& Outputs) const
{
    Outputs.SetFromROS2(motion_primitive_sequence_msg);
}

void* UROS2MotionPrimitiveSequenceMsg::Get()
{
	return &motion_primitive_sequence_msg;
}

FString UROS2MotionPrimitiveSequenceMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}