// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from clf_audio_msgs/msg/AudioInfo.msg - do not modify

#include "Msgs/ROS2AudioInfo.h"

#include "Kismet/GameplayStatics.h"



void UROS2AudioInfoMsg::Init()
{
	clf_audio_msgs__msg__AudioInfo__init(&audio_info_msg);
}

void UROS2AudioInfoMsg::Fini()
{
	clf_audio_msgs__msg__AudioInfo__fini(&audio_info_msg);
}

const rosidl_message_type_support_t* UROS2AudioInfoMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(clf_audio_msgs, msg, AudioInfo);
}

void UROS2AudioInfoMsg::SetMsg(const FROSAudioInfo& Inputs)
{
    Inputs.SetROS2(audio_info_msg);
}

void UROS2AudioInfoMsg::GetMsg(FROSAudioInfo& Outputs) const
{
    Outputs.SetFromROS2(audio_info_msg);
}

void* UROS2AudioInfoMsg::Get()
{
	return &audio_info_msg;
}

FString UROS2AudioInfoMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}