// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/PidState.msg - do not modify

#include "Msgs/ROS2PidState.h"

#include "Kismet/GameplayStatics.h"



void UROS2PidStateMsg::Init()
{
	control_msgs__msg__PidState__init(&pid_state_msg);
}

void UROS2PidStateMsg::Fini()
{
	control_msgs__msg__PidState__fini(&pid_state_msg);
}

const rosidl_message_type_support_t* UROS2PidStateMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, PidState);
}

void UROS2PidStateMsg::SetMsg(const FROSPidState& Inputs)
{
    Inputs.SetROS2(pid_state_msg);
}

void UROS2PidStateMsg::GetMsg(FROSPidState& Outputs) const
{
    Outputs.SetFromROS2(pid_state_msg);
}

void* UROS2PidStateMsg::Get()
{
	return &pid_state_msg;
}

FString UROS2PidStateMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}