// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from clf_audio_msgs/msg/AudioData.msg - do not modify

#include "Msgs/ROS2AudioData.h"

#include "Kismet/GameplayStatics.h"



void UROS2AudioDataMsg::Init()
{
	clf_audio_msgs__msg__AudioData__init(&audio_data_msg);
}

void UROS2AudioDataMsg::Fini()
{
	clf_audio_msgs__msg__AudioData__fini(&audio_data_msg);
}

const rosidl_message_type_support_t* UROS2AudioDataMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(clf_audio_msgs, msg, AudioData);
}

void UROS2AudioDataMsg::SetMsg(const FROSAudioData& Inputs)
{
    Inputs.SetROS2(audio_data_msg);
}

void UROS2AudioDataMsg::GetMsg(FROSAudioData& Outputs) const
{
    Outputs.SetFromROS2(audio_data_msg);
}

void* UROS2AudioDataMsg::Get()
{
	return &audio_data_msg;
}

FString UROS2AudioDataMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}