// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from clf_ue_audio_msgs/msg/ReturnCode.msg - do not modify

#include "Msgs/ROS2ReturnCode.h"

#include "Kismet/GameplayStatics.h"



void UROS2ReturnCodeMsg::Init()
{
	clf_ue_audio_msgs__msg__ReturnCode__init(&return_code_msg);
}

void UROS2ReturnCodeMsg::Fini()
{
	clf_ue_audio_msgs__msg__ReturnCode__fini(&return_code_msg);
}

const rosidl_message_type_support_t* UROS2ReturnCodeMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(clf_ue_audio_msgs, msg, ReturnCode);
}

void UROS2ReturnCodeMsg::SetMsg(const FROSReturnCode& Inputs)
{
    Inputs.SetROS2(return_code_msg);
}

void UROS2ReturnCodeMsg::GetMsg(FROSReturnCode& Outputs) const
{
    Outputs.SetFromROS2(return_code_msg);
}

void* UROS2ReturnCodeMsg::Get()
{
	return &return_code_msg;
}

FString UROS2ReturnCodeMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}