// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/JointTrajectoryControllerState.msg - do not modify

#include "Msgs/ROS2JointTrajCtrllerState.h"

#include "Kismet/GameplayStatics.h"



void UROS2JointTrajCtrllerStateMsg::Init()
{
	control_msgs__msg__JointTrajectoryControllerState__init(&joint_trajectory_controller_state_msg);
}

void UROS2JointTrajCtrllerStateMsg::Fini()
{
	control_msgs__msg__JointTrajectoryControllerState__fini(&joint_trajectory_controller_state_msg);
}

const rosidl_message_type_support_t* UROS2JointTrajCtrllerStateMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, JointTrajectoryControllerState);
}

void UROS2JointTrajCtrllerStateMsg::SetMsg(const FROSJointTrajCtrllerState& Inputs)
{
    Inputs.SetROS2(joint_trajectory_controller_state_msg);
}

void UROS2JointTrajCtrllerStateMsg::GetMsg(FROSJointTrajCtrllerState& Outputs) const
{
    Outputs.SetFromROS2(joint_trajectory_controller_state_msg);
}

void* UROS2JointTrajCtrllerStateMsg::Get()
{
	return &joint_trajectory_controller_state_msg;
}

FString UROS2JointTrajCtrllerStateMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}