// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/InterfaceValue.msg - do not modify

#include "Msgs/ROS2InterfaceValue.h"

#include "Kismet/GameplayStatics.h"



void UROS2InterfaceValueMsg::Init()
{
	control_msgs__msg__InterfaceValue__init(&interface_value_msg);
}

void UROS2InterfaceValueMsg::Fini()
{
	control_msgs__msg__InterfaceValue__fini(&interface_value_msg);
}

const rosidl_message_type_support_t* UROS2InterfaceValueMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, InterfaceValue);
}

void UROS2InterfaceValueMsg::SetMsg(const FROSInterfaceValue& Inputs)
{
    Inputs.SetROS2(interface_value_msg);
}

void UROS2InterfaceValueMsg::GetMsg(FROSInterfaceValue& Outputs) const
{
    Outputs.SetFromROS2(interface_value_msg);
}

void* UROS2InterfaceValueMsg::Get()
{
	return &interface_value_msg;
}

FString UROS2InterfaceValueMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}