// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/MotionPrimitive.msg - do not modify

#include "Msgs/ROS2MotionPrimitive.h"

#include "Kismet/GameplayStatics.h"



void UROS2MotionPrimitiveMsg::Init()
{
	control_msgs__msg__MotionPrimitive__init(&motion_primitive_msg);
}

void UROS2MotionPrimitiveMsg::Fini()
{
	control_msgs__msg__MotionPrimitive__fini(&motion_primitive_msg);
}

const rosidl_message_type_support_t* UROS2MotionPrimitiveMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, MotionPrimitive);
}

void UROS2MotionPrimitiveMsg::SetMsg(const FROSMotionPrimitive& Inputs)
{
    Inputs.SetROS2(motion_primitive_msg);
}

void UROS2MotionPrimitiveMsg::GetMsg(FROSMotionPrimitive& Outputs) const
{
    Outputs.SetFromROS2(motion_primitive_msg);
}

void* UROS2MotionPrimitiveMsg::Get()
{
	return &motion_primitive_msg;
}

FString UROS2MotionPrimitiveMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}