// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/DynamicInterfaceValues.msg - do not modify

#include "Msgs/ROS2DynamicInterfaceValues.h"

#include "Kismet/GameplayStatics.h"



void UROS2DynamicInterfaceValuesMsg::Init()
{
	control_msgs__msg__DynamicInterfaceValues__init(&dynamic_interface_values_msg);
}

void UROS2DynamicInterfaceValuesMsg::Fini()
{
	control_msgs__msg__DynamicInterfaceValues__fini(&dynamic_interface_values_msg);
}

const rosidl_message_type_support_t* UROS2DynamicInterfaceValuesMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, DynamicInterfaceValues);
}

void UROS2DynamicInterfaceValuesMsg::SetMsg(const FROSDynamicInterfaceValues& Inputs)
{
    Inputs.SetROS2(dynamic_interface_values_msg);
}

void UROS2DynamicInterfaceValuesMsg::GetMsg(FROSDynamicInterfaceValues& Outputs) const
{
    Outputs.SetFromROS2(dynamic_interface_values_msg);
}

void* UROS2DynamicInterfaceValuesMsg::Get()
{
	return &dynamic_interface_values_msg;
}

FString UROS2DynamicInterfaceValuesMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}