// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/JointControllerState.msg - do not modify

#include "Msgs/ROS2JointCtrllerState.h"

#include "Kismet/GameplayStatics.h"



void UROS2JointCtrllerStateMsg::Init()
{
	control_msgs__msg__JointControllerState__init(&joint_controller_state_msg);
}

void UROS2JointCtrllerStateMsg::Fini()
{
	control_msgs__msg__JointControllerState__fini(&joint_controller_state_msg);
}

const rosidl_message_type_support_t* UROS2JointCtrllerStateMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, JointControllerState);
}

void UROS2JointCtrllerStateMsg::SetMsg(const FROSJointCtrllerState& Inputs)
{
    Inputs.SetROS2(joint_controller_state_msg);
}

void UROS2JointCtrllerStateMsg::GetMsg(FROSJointCtrllerState& Outputs) const
{
    Outputs.SetFromROS2(joint_controller_state_msg);
}

void* UROS2JointCtrllerStateMsg::Get()
{
	return &joint_controller_state_msg;
}

FString UROS2JointCtrllerStateMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}