// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/MultiDOFStateStamped.msg - do not modify

#include "Msgs/ROS2MultiDOFStateStamped.h"

#include "Kismet/GameplayStatics.h"



void UROS2MultiDOFStateStampedMsg::Init()
{
	control_msgs__msg__MultiDOFStateStamped__init(&multi_dof_state_stamped_msg);
}

void UROS2MultiDOFStateStampedMsg::Fini()
{
	control_msgs__msg__MultiDOFStateStamped__fini(&multi_dof_state_stamped_msg);
}

const rosidl_message_type_support_t* UROS2MultiDOFStateStampedMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, MultiDOFStateStamped);
}

void UROS2MultiDOFStateStampedMsg::SetMsg(const FROSMultiDOFStateStamped& Inputs)
{
    Inputs.SetROS2(multi_dof_state_stamped_msg);
}

void UROS2MultiDOFStateStampedMsg::GetMsg(FROSMultiDOFStateStamped& Outputs) const
{
    Outputs.SetFromROS2(multi_dof_state_stamped_msg);
}

void* UROS2MultiDOFStateStampedMsg::Get()
{
	return &multi_dof_state_stamped_msg;
}

FString UROS2MultiDOFStateStampedMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}