// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/JointJog.msg - do not modify

#include "Msgs/ROS2JointJog.h"

#include "Kismet/GameplayStatics.h"



void UROS2JointJogMsg::Init()
{
	control_msgs__msg__JointJog__init(&joint_jog_msg);
}

void UROS2JointJogMsg::Fini()
{
	control_msgs__msg__JointJog__fini(&joint_jog_msg);
}

const rosidl_message_type_support_t* UROS2JointJogMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, JointJog);
}

void UROS2JointJogMsg::SetMsg(const FROSJointJog& Inputs)
{
    Inputs.SetROS2(joint_jog_msg);
}

void UROS2JointJogMsg::GetMsg(FROSJointJog& Outputs) const
{
    Outputs.SetFromROS2(joint_jog_msg);
}

void* UROS2JointJogMsg::Get()
{
	return &joint_jog_msg;
}

FString UROS2JointJogMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}