// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/SpeedScalingFactor.msg - do not modify

#include "Msgs/ROS2SpeedScalingFactor.h"

#include "Kismet/GameplayStatics.h"



void UROS2SpeedScalingFactorMsg::Init()
{
	control_msgs__msg__SpeedScalingFactor__init(&speed_scaling_factor_msg);
}

void UROS2SpeedScalingFactorMsg::Fini()
{
	control_msgs__msg__SpeedScalingFactor__fini(&speed_scaling_factor_msg);
}

const rosidl_message_type_support_t* UROS2SpeedScalingFactorMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, SpeedScalingFactor);
}

void UROS2SpeedScalingFactorMsg::SetMsg(const FROSSpeedScalingFactor& Inputs)
{
    Inputs.SetROS2(speed_scaling_factor_msg);
}

void UROS2SpeedScalingFactorMsg::GetMsg(FROSSpeedScalingFactor& Outputs) const
{
    Outputs.SetFromROS2(speed_scaling_factor_msg);
}

void* UROS2SpeedScalingFactorMsg::Get()
{
	return &speed_scaling_factor_msg;
}

FString UROS2SpeedScalingFactorMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}