// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/JointTolerance.msg - do not modify

#include "Msgs/ROS2JointTolerance.h"

#include "Kismet/GameplayStatics.h"



void UROS2JointToleranceMsg::Init()
{
	control_msgs__msg__JointTolerance__init(&joint_tolerance_msg);
}

void UROS2JointToleranceMsg::Fini()
{
	control_msgs__msg__JointTolerance__fini(&joint_tolerance_msg);
}

const rosidl_message_type_support_t* UROS2JointToleranceMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, JointTolerance);
}

void UROS2JointToleranceMsg::SetMsg(const FROSJointTolerance& Inputs)
{
    Inputs.SetROS2(joint_tolerance_msg);
}

void UROS2JointToleranceMsg::GetMsg(FROSJointTolerance& Outputs) const
{
    Outputs.SetFromROS2(joint_tolerance_msg);
}

void* UROS2JointToleranceMsg::Get()
{
	return &joint_tolerance_msg;
}

FString UROS2JointToleranceMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}