// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/MotionArgument.msg - do not modify

#include "Msgs/ROS2MotionArgument.h"

#include "Kismet/GameplayStatics.h"



void UROS2MotionArgumentMsg::Init()
{
	control_msgs__msg__MotionArgument__init(&motion_argument_msg);
}

void UROS2MotionArgumentMsg::Fini()
{
	control_msgs__msg__MotionArgument__fini(&motion_argument_msg);
}

const rosidl_message_type_support_t* UROS2MotionArgumentMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, MotionArgument);
}

void UROS2MotionArgumentMsg::SetMsg(const FROSMotionArgument& Inputs)
{
    Inputs.SetROS2(motion_argument_msg);
}

void UROS2MotionArgumentMsg::GetMsg(FROSMotionArgument& Outputs) const
{
    Outputs.SetFromROS2(motion_argument_msg);
}

void* UROS2MotionArgumentMsg::Get()
{
	return &motion_argument_msg;
}

FString UROS2MotionArgumentMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}