// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/SingleDOFState.msg - do not modify

#include "Msgs/ROS2SingleDOFState.h"

#include "Kismet/GameplayStatics.h"



void UROS2SingleDOFStateMsg::Init()
{
	control_msgs__msg__SingleDOFState__init(&single_dof_state_msg);
}

void UROS2SingleDOFStateMsg::Fini()
{
	control_msgs__msg__SingleDOFState__fini(&single_dof_state_msg);
}

const rosidl_message_type_support_t* UROS2SingleDOFStateMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, SingleDOFState);
}

void UROS2SingleDOFStateMsg::SetMsg(const FROSSingleDOFState& Inputs)
{
    Inputs.SetROS2(single_dof_state_msg);
}

void UROS2SingleDOFStateMsg::GetMsg(FROSSingleDOFState& Outputs) const
{
    Outputs.SetFromROS2(single_dof_state_msg);
}

void* UROS2SingleDOFStateMsg::Get()
{
	return &single_dof_state_msg;
}

FString UROS2SingleDOFStateMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}