// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/DynamicInterfaceGroupValues.msg - do not modify

#include "Msgs/ROS2DynamicInterfaceGroupValues.h"

#include "Kismet/GameplayStatics.h"



void UROS2DynamicInterfaceGroupValuesMsg::Init()
{
	control_msgs__msg__DynamicInterfaceGroupValues__init(&dynamic_interface_group_values_msg);
}

void UROS2DynamicInterfaceGroupValuesMsg::Fini()
{
	control_msgs__msg__DynamicInterfaceGroupValues__fini(&dynamic_interface_group_values_msg);
}

const rosidl_message_type_support_t* UROS2DynamicInterfaceGroupValuesMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, DynamicInterfaceGroupValues);
}

void UROS2DynamicInterfaceGroupValuesMsg::SetMsg(const FROSDynamicInterfaceGroupValues& Inputs)
{
    Inputs.SetROS2(dynamic_interface_group_values_msg);
}

void UROS2DynamicInterfaceGroupValuesMsg::GetMsg(FROSDynamicInterfaceGroupValues& Outputs) const
{
    Outputs.SetFromROS2(dynamic_interface_group_values_msg);
}

void* UROS2DynamicInterfaceGroupValuesMsg::Get()
{
	return &dynamic_interface_group_values_msg;
}

FString UROS2DynamicInterfaceGroupValuesMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}