// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from clf_ue_audio_msgs/msg/CurrentStatus.msg - do not modify

#include "Msgs/ROS2CurrentStatus.h"

#include "Kismet/GameplayStatics.h"



void UROS2CurrentStatusMsg::Init()
{
	clf_ue_audio_msgs__msg__CurrentStatus__init(&current_status_msg);
}

void UROS2CurrentStatusMsg::Fini()
{
	clf_ue_audio_msgs__msg__CurrentStatus__fini(&current_status_msg);
}

const rosidl_message_type_support_t* UROS2CurrentStatusMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(clf_ue_audio_msgs, msg, CurrentStatus);
}

void UROS2CurrentStatusMsg::SetMsg(const FROSCurrentStatus& Inputs)
{
    Inputs.SetROS2(current_status_msg);
}

void UROS2CurrentStatusMsg::GetMsg(FROSCurrentStatus& Outputs) const
{
    Outputs.SetFromROS2(current_status_msg);
}

void* UROS2CurrentStatusMsg::Get()
{
	return &current_status_msg;
}

FString UROS2CurrentStatusMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}