// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/JointComponentTolerance.msg - do not modify

#include "Msgs/ROS2JointComponentTolerance.h"

#include "Kismet/GameplayStatics.h"



void UROS2JointComponentToleranceMsg::Init()
{
	control_msgs__msg__JointComponentTolerance__init(&joint_component_tolerance_msg);
}

void UROS2JointComponentToleranceMsg::Fini()
{
	control_msgs__msg__JointComponentTolerance__fini(&joint_component_tolerance_msg);
}

const rosidl_message_type_support_t* UROS2JointComponentToleranceMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, JointComponentTolerance);
}

void UROS2JointComponentToleranceMsg::SetMsg(const FROSJointComponentTolerance& Inputs)
{
    Inputs.SetROS2(joint_component_tolerance_msg);
}

void UROS2JointComponentToleranceMsg::GetMsg(FROSJointComponentTolerance& Outputs) const
{
    Outputs.SetFromROS2(joint_component_tolerance_msg);
}

void* UROS2JointComponentToleranceMsg::Get()
{
	return &joint_component_tolerance_msg;
}

FString UROS2JointComponentToleranceMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}