// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/DynamicJointState.msg - do not modify

#include "Msgs/ROS2DynamicJointState.h"

#include "Kismet/GameplayStatics.h"



void UROS2DynamicJointStateMsg::Init()
{
	control_msgs__msg__DynamicJointState__init(&dynamic_joint_state_msg);
}

void UROS2DynamicJointStateMsg::Fini()
{
	control_msgs__msg__DynamicJointState__fini(&dynamic_joint_state_msg);
}

const rosidl_message_type_support_t* UROS2DynamicJointStateMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, DynamicJointState);
}

void UROS2DynamicJointStateMsg::SetMsg(const FROSDynamicJointState& Inputs)
{
    Inputs.SetROS2(dynamic_joint_state_msg);
}

void UROS2DynamicJointStateMsg::GetMsg(FROSDynamicJointState& Outputs) const
{
    Outputs.SetFromROS2(dynamic_joint_state_msg);
}

void* UROS2DynamicJointStateMsg::Get()
{
	return &dynamic_joint_state_msg;
}

FString UROS2DynamicJointStateMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}