// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/SingleDOFStateStamped.msg - do not modify

#include "Msgs/ROS2SingleDOFStateStamped.h"

#include "Kismet/GameplayStatics.h"



void UROS2SingleDOFStateStampedMsg::Init()
{
	control_msgs__msg__SingleDOFStateStamped__init(&single_dof_state_stamped_msg);
}

void UROS2SingleDOFStateStampedMsg::Fini()
{
	control_msgs__msg__SingleDOFStateStamped__fini(&single_dof_state_stamped_msg);
}

const rosidl_message_type_support_t* UROS2SingleDOFStateStampedMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, SingleDOFStateStamped);
}

void UROS2SingleDOFStateStampedMsg::SetMsg(const FROSSingleDOFStateStamped& Inputs)
{
    Inputs.SetROS2(single_dof_state_stamped_msg);
}

void UROS2SingleDOFStateStampedMsg::GetMsg(FROSSingleDOFStateStamped& Outputs) const
{
    Outputs.SetFromROS2(single_dof_state_stamped_msg);
}

void* UROS2SingleDOFStateStampedMsg::Get()
{
	return &single_dof_state_stamped_msg;
}

FString UROS2SingleDOFStateStampedMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}