// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/GripperCommand.msg - do not modify

#include "Msgs/ROS2GripperCommand.h"

#include "Kismet/GameplayStatics.h"



void UROS2GripperCommandMsg::Init()
{
	control_msgs__msg__GripperCommand__init(&gripper_command_msg);
}

void UROS2GripperCommandMsg::Fini()
{
	control_msgs__msg__GripperCommand__fini(&gripper_command_msg);
}

const rosidl_message_type_support_t* UROS2GripperCommandMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, GripperCommand);
}

void UROS2GripperCommandMsg::SetMsg(const FROSGripperCommand& Inputs)
{
    Inputs.SetROS2(gripper_command_msg);
}

void UROS2GripperCommandMsg::GetMsg(FROSGripperCommand& Outputs) const
{
    Outputs.SetFromROS2(gripper_command_msg);
}

void* UROS2GripperCommandMsg::Get()
{
	return &gripper_command_msg;
}

FString UROS2GripperCommandMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}