// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/SteeringControllerStatus.msg - do not modify

#include "Msgs/ROS2SteeringCtrllerStatus.h"

#include "Kismet/GameplayStatics.h"



void UROS2SteeringCtrllerStatusMsg::Init()
{
	control_msgs__msg__SteeringControllerStatus__init(&steering_controller_status_msg);
}

void UROS2SteeringCtrllerStatusMsg::Fini()
{
	control_msgs__msg__SteeringControllerStatus__fini(&steering_controller_status_msg);
}

const rosidl_message_type_support_t* UROS2SteeringCtrllerStatusMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, SteeringControllerStatus);
}

void UROS2SteeringCtrllerStatusMsg::SetMsg(const FROSSteeringCtrllerStatus& Inputs)
{
    Inputs.SetROS2(steering_controller_status_msg);
}

void UROS2SteeringCtrllerStatusMsg::GetMsg(FROSSteeringCtrllerStatus& Outputs) const
{
    Outputs.SetFromROS2(steering_controller_status_msg);
}

void* UROS2SteeringCtrllerStatusMsg::Get()
{
	return &steering_controller_status_msg;
}

FString UROS2SteeringCtrllerStatusMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}