// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/MultiDOFCommand.msg - do not modify

#include "Msgs/ROS2MultiDOFCommand.h"

#include "Kismet/GameplayStatics.h"



void UROS2MultiDOFCommandMsg::Init()
{
	control_msgs__msg__MultiDOFCommand__init(&multi_dof_command_msg);
}

void UROS2MultiDOFCommandMsg::Fini()
{
	control_msgs__msg__MultiDOFCommand__fini(&multi_dof_command_msg);
}

const rosidl_message_type_support_t* UROS2MultiDOFCommandMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, MultiDOFCommand);
}

void UROS2MultiDOFCommandMsg::SetMsg(const FROSMultiDOFCommand& Inputs)
{
    Inputs.SetROS2(multi_dof_command_msg);
}

void UROS2MultiDOFCommandMsg::GetMsg(FROSMultiDOFCommand& Outputs) const
{
    Outputs.SetFromROS2(multi_dof_command_msg);
}

void* UROS2MultiDOFCommandMsg::Get()
{
	return &multi_dof_command_msg;
}

FString UROS2MultiDOFCommandMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}