// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from control_msgs/msg/MecanumDriveControllerState.msg - do not modify

#include "Msgs/ROS2MecanumDriveCtrllerState.h"

#include "Kismet/GameplayStatics.h"



void UROS2MecanumDriveCtrllerStateMsg::Init()
{
	control_msgs__msg__MecanumDriveControllerState__init(&mecanum_drive_controller_state_msg);
}

void UROS2MecanumDriveCtrllerStateMsg::Fini()
{
	control_msgs__msg__MecanumDriveControllerState__fini(&mecanum_drive_controller_state_msg);
}

const rosidl_message_type_support_t* UROS2MecanumDriveCtrllerStateMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(control_msgs, msg, MecanumDriveControllerState);
}

void UROS2MecanumDriveCtrllerStateMsg::SetMsg(const FROSMecanumDriveCtrllerState& Inputs)
{
    Inputs.SetROS2(mecanum_drive_controller_state_msg);
}

void UROS2MecanumDriveCtrllerStateMsg::GetMsg(FROSMecanumDriveCtrllerState& Outputs) const
{
    Outputs.SetFromROS2(mecanum_drive_controller_state_msg);
}

void* UROS2MecanumDriveCtrllerStateMsg::Get()
{
	return &mecanum_drive_controller_state_msg;
}

FString UROS2MecanumDriveCtrllerStateMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}